//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 09:54:43 PM CET 
//


package com.mobissime.forms.objects;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Block complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Block">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}DataSourceArgument" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}DataSourceColumn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}Item" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}Relation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}Trigger" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="DatabaseBlock" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DeleteAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DirtyInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DMLReturnValue" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="EnforcedColumnSecurity" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="EnforcedPrimaryKey" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="IncludeRefitem" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="InsertAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="PrecompSummary" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="QueryAllRecords" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="QueryAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ReverseDirection" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ShowScrollbar" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="SingleRecord" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="SubclassObjectGroup" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="UpdateAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="UpdateChangedColumns" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DMLArraySize" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="DMLDataType" type="{http://xmlns.oracle.com/Forms}DMLDataTypeType" />
 *       &lt;attribute name="KeyMode" type="{http://xmlns.oracle.com/Forms}KeyModeType" />
 *       &lt;attribute name="LanguageDirection" type="{http://xmlns.oracle.com/Forms}LanguageDirectionType" />
 *       &lt;attribute name="LockMode" type="{http://xmlns.oracle.com/Forms}LockModeType" />
 *       &lt;attribute name="MaximumQueryTime" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="MaximumRecordsFetched" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="NavigationStyle" type="{http://xmlns.oracle.com/Forms}NavigationStyleType" />
 *       &lt;attribute name="ParentModuleType" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ParentType" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="PersistentClientInfoLength" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="QueryDataSourceType" type="{http://xmlns.oracle.com/Forms}QueryDataSourceTypeType" />
 *       &lt;attribute name="RecordOrientation" type="{http://xmlns.oracle.com/Forms}RecordOrientationType" />
 *       &lt;attribute name="RecordsBufferedCount" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="RecordsDisplayCount" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="RecordsFetchedCount" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ScrollbarLength" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ScrollbarOrientation" type="{http://xmlns.oracle.com/Forms}ScrollbarOrientationType" />
 *       &lt;attribute name="ScrollbarWidth" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ScrollbarXPosition" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ScrollbarYPosition" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Alias" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BackColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DeleteProcedureName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DMLDataName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FillPattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ForegroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="InsertProcedureName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LockProcedureName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" use="required" type="{http://xmlns.oracle.com/Forms}nameType" />
 *       &lt;attribute name="NextNavigationBlockName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OptionHint" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OrderByClause" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentFilename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentFilepath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentModule" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PreviousNavigationBlockName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="QueryDataSourceName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RecordVisualAttributeGroupName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ScrollbarCanvasName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ScrollbarTabPageName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="UpdateProcedureName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="VisualAttributeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="WhereClause" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SmartClass" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Block", propOrder = {
    "dataSourceArgumentOrDataSourceColumnOrItem"
})
public class Block {

    @XmlElements({
        @XmlElement(name = "DataSourceArgument", type = DataSourceArgument.class),
        @XmlElement(name = "DataSourceColumn", type = DataSourceColumn.class),
        @XmlElement(name = "Item", type = Item.class),
        @XmlElement(name = "Relation", type = Relation.class),
        @XmlElement(name = "Trigger", type = Trigger.class)
    })
    protected List<Object> dataSourceArgumentOrDataSourceColumnOrItem;
    @XmlAttribute(name = "DatabaseBlock")
    protected Boolean databaseBlock;
    @XmlAttribute(name = "DeleteAllowed")
    protected Boolean deleteAllowed;
    @XmlAttribute(name = "DirtyInfo")
    protected Boolean dirtyInfo;
    @XmlAttribute(name = "DMLReturnValue")
    protected Boolean dmlReturnValue;
    @XmlAttribute(name = "EnforcedColumnSecurity")
    protected Boolean enforcedColumnSecurity;
    @XmlAttribute(name = "EnforcedPrimaryKey")
    protected Boolean enforcedPrimaryKey;
    @XmlAttribute(name = "IncludeRefitem")
    protected Boolean includeRefitem;
    @XmlAttribute(name = "InsertAllowed")
    protected Boolean insertAllowed;
    @XmlAttribute(name = "PrecompSummary")
    protected Boolean precompSummary;
    @XmlAttribute(name = "QueryAllRecords")
    protected Boolean queryAllRecords;
    @XmlAttribute(name = "QueryAllowed")
    protected Boolean queryAllowed;
    @XmlAttribute(name = "ReverseDirection")
    protected Boolean reverseDirection;
    @XmlAttribute(name = "ShowScrollbar")
    protected Boolean showScrollbar;
    @XmlAttribute(name = "SingleRecord")
    protected Boolean singleRecord;
    @XmlAttribute(name = "SubclassObjectGroup")
    protected Boolean subclassObjectGroup;
    @XmlAttribute(name = "UpdateAllowed")
    protected Boolean updateAllowed;
    @XmlAttribute(name = "UpdateChangedColumns")
    protected Boolean updateChangedColumns;
    @XmlAttribute(name = "DMLArraySize")
    protected BigInteger dmlArraySize;
    @XmlAttribute(name = "DMLDataType")
    protected String dmlDataType;
    @XmlAttribute(name = "KeyMode")
    protected String keyMode;
    @XmlAttribute(name = "LanguageDirection")
    protected String languageDirection;
    @XmlAttribute(name = "LockMode")
    protected String lockMode;
    @XmlAttribute(name = "MaximumQueryTime")
    protected BigInteger maximumQueryTime;
    @XmlAttribute(name = "MaximumRecordsFetched")
    protected BigInteger maximumRecordsFetched;
    @XmlAttribute(name = "NavigationStyle")
    protected String navigationStyle;
    @XmlAttribute(name = "ParentModuleType")
    protected BigInteger parentModuleType;
    @XmlAttribute(name = "ParentType")
    protected BigInteger parentType;
    @XmlAttribute(name = "PersistentClientInfoLength")
    protected BigInteger persistentClientInfoLength;
    @XmlAttribute(name = "QueryDataSourceType")
    protected String queryDataSourceType;
    @XmlAttribute(name = "RecordOrientation")
    protected String recordOrientation;
    @XmlAttribute(name = "RecordsBufferedCount")
    protected BigInteger recordsBufferedCount;
    @XmlAttribute(name = "RecordsDisplayCount")
    protected BigInteger recordsDisplayCount;
    @XmlAttribute(name = "RecordsFetchedCount")
    protected BigInteger recordsFetchedCount;
    @XmlAttribute(name = "ScrollbarLength")
    protected BigInteger scrollbarLength;
    @XmlAttribute(name = "ScrollbarOrientation")
    protected String scrollbarOrientation;
    @XmlAttribute(name = "ScrollbarWidth")
    protected BigInteger scrollbarWidth;
    @XmlAttribute(name = "ScrollbarXPosition")
    protected BigInteger scrollbarXPosition;
    @XmlAttribute(name = "ScrollbarYPosition")
    protected BigInteger scrollbarYPosition;
    @XmlAttribute(name = "Alias")
    protected String alias;
    @XmlAttribute(name = "BackColor")
    protected String backColor;
    @XmlAttribute(name = "Comment")
    protected String comment;
    @XmlAttribute(name = "DeleteProcedureName")
    protected String deleteProcedureName;
    @XmlAttribute(name = "DMLDataName")
    protected String dmlDataName;
    @XmlAttribute(name = "FillPattern")
    protected String fillPattern;
    @XmlAttribute(name = "ForegroundColor")
    protected String foregroundColor;
    @XmlAttribute(name = "InsertProcedureName")
    protected String insertProcedureName;
    @XmlAttribute(name = "LockProcedureName")
    protected String lockProcedureName;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "NextNavigationBlockName")
    protected String nextNavigationBlockName;
    @XmlAttribute(name = "OptionHint")
    protected String optionHint;
    @XmlAttribute(name = "OrderByClause")
    protected String orderByClause;
    @XmlAttribute(name = "ParentFilename")
    protected String parentFilename;
    @XmlAttribute(name = "ParentFilepath")
    protected String parentFilepath;
    @XmlAttribute(name = "ParentModule")
    protected String parentModule;
    @XmlAttribute(name = "ParentName")
    protected String parentName;
    @XmlAttribute(name = "PreviousNavigationBlockName")
    protected String previousNavigationBlockName;
    @XmlAttribute(name = "QueryDataSourceName")
    protected String queryDataSourceName;
    @XmlAttribute(name = "RecordVisualAttributeGroupName")
    protected String recordVisualAttributeGroupName;
    @XmlAttribute(name = "ScrollbarCanvasName")
    protected String scrollbarCanvasName;
    @XmlAttribute(name = "ScrollbarTabPageName")
    protected String scrollbarTabPageName;
    @XmlAttribute(name = "UpdateProcedureName")
    protected String updateProcedureName;
    @XmlAttribute(name = "VisualAttributeName")
    protected String visualAttributeName;
    @XmlAttribute(name = "WhereClause")
    protected String whereClause;
    @XmlAttribute(name = "SmartClass")
    protected Boolean smartClass;

    /** Custom fields */
    @XmlAttribute(name = "TriggersNumber")
    protected int numberOfTriggers;

    /**
     * Gets the value of the dataSourceArgumentOrDataSourceColumnOrItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataSourceArgumentOrDataSourceColumnOrItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataSourceArgumentOrDataSourceColumnOrItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataSourceArgument }
     * {@link DataSourceColumn }
     * {@link Item }
     * {@link Relation }
     * {@link Trigger }
     * 
     * 
     */
    public List<Object> getDataSourceArgumentOrDataSourceColumnOrItem() {
        if (dataSourceArgumentOrDataSourceColumnOrItem == null) {
            dataSourceArgumentOrDataSourceColumnOrItem = new ArrayList<Object>();
        }
        return this.dataSourceArgumentOrDataSourceColumnOrItem;
    }

    /**
     * Gets the value of the databaseBlock property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDatabaseBlock() {
        return databaseBlock;
    }

    /**
     * Sets the value of the databaseBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDatabaseBlock(Boolean value) {
        this.databaseBlock = value;
    }

    /**
     * Gets the value of the deleteAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeleteAllowed() {
        return deleteAllowed;
    }

    /**
     * Sets the value of the deleteAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeleteAllowed(Boolean value) {
        this.deleteAllowed = value;
    }

    /**
     * Gets the value of the dirtyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDirtyInfo() {
        return dirtyInfo;
    }

    /**
     * Sets the value of the dirtyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDirtyInfo(Boolean value) {
        this.dirtyInfo = value;
    }

    /**
     * Gets the value of the dmlReturnValue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDMLReturnValue() {
        return dmlReturnValue;
    }

    /**
     * Sets the value of the dmlReturnValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDMLReturnValue(Boolean value) {
        this.dmlReturnValue = value;
    }

    /**
     * Gets the value of the enforcedColumnSecurity property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnforcedColumnSecurity() {
        return enforcedColumnSecurity;
    }

    /**
     * Sets the value of the enforcedColumnSecurity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnforcedColumnSecurity(Boolean value) {
        this.enforcedColumnSecurity = value;
    }

    /**
     * Gets the value of the enforcedPrimaryKey property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnforcedPrimaryKey() {
        return enforcedPrimaryKey;
    }

    /**
     * Sets the value of the enforcedPrimaryKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnforcedPrimaryKey(Boolean value) {
        this.enforcedPrimaryKey = value;
    }

    /**
     * Gets the value of the includeRefitem property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeRefitem() {
        return includeRefitem;
    }

    /**
     * Sets the value of the includeRefitem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeRefitem(Boolean value) {
        this.includeRefitem = value;
    }

    /**
     * Gets the value of the insertAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInsertAllowed() {
        return insertAllowed;
    }

    /**
     * Sets the value of the insertAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInsertAllowed(Boolean value) {
        this.insertAllowed = value;
    }

    /**
     * Gets the value of the precompSummary property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrecompSummary() {
        return precompSummary;
    }

    /**
     * Sets the value of the precompSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrecompSummary(Boolean value) {
        this.precompSummary = value;
    }

    /**
     * Gets the value of the queryAllRecords property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isQueryAllRecords() {
        return queryAllRecords;
    }

    /**
     * Sets the value of the queryAllRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setQueryAllRecords(Boolean value) {
        this.queryAllRecords = value;
    }

    /**
     * Gets the value of the queryAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isQueryAllowed() {
        return queryAllowed;
    }

    /**
     * Sets the value of the queryAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setQueryAllowed(Boolean value) {
        this.queryAllowed = value;
    }

    /**
     * Gets the value of the reverseDirection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReverseDirection() {
        return reverseDirection;
    }

    /**
     * Sets the value of the reverseDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReverseDirection(Boolean value) {
        this.reverseDirection = value;
    }

    /**
     * Gets the value of the showScrollbar property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowScrollbar() {
        return showScrollbar;
    }

    /**
     * Sets the value of the showScrollbar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowScrollbar(Boolean value) {
        this.showScrollbar = value;
    }

    /**
     * Gets the value of the singleRecord property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSingleRecord() {
        return singleRecord;
    }

    /**
     * Sets the value of the singleRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSingleRecord(Boolean value) {
        this.singleRecord = value;
    }

    /**
     * Gets the value of the subclassObjectGroup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSubclassObjectGroup() {
        return subclassObjectGroup;
    }

    /**
     * Sets the value of the subclassObjectGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSubclassObjectGroup(Boolean value) {
        this.subclassObjectGroup = value;
    }

    /**
     * Gets the value of the updateAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUpdateAllowed() {
        return updateAllowed;
    }

    /**
     * Sets the value of the updateAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUpdateAllowed(Boolean value) {
        this.updateAllowed = value;
    }

    /**
     * Gets the value of the updateChangedColumns property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUpdateChangedColumns() {
        return updateChangedColumns;
    }

    /**
     * Sets the value of the updateChangedColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUpdateChangedColumns(Boolean value) {
        this.updateChangedColumns = value;
    }

    /**
     * Gets the value of the dmlArraySize property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getDMLArraySize() {
        return dmlArraySize;
    }

    /**
     * Sets the value of the dmlArraySize property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setDMLArraySize(BigInteger value) {
        this.dmlArraySize = value;
    }

    /**
     * Gets the value of the dmlDataType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDMLDataType() {
        return dmlDataType;
    }

    /**
     * Sets the value of the dmlDataType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDMLDataType(String value) {
        this.dmlDataType = value;
    }

    /**
     * Gets the value of the keyMode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKeyMode() {
        return keyMode;
    }

    /**
     * Sets the value of the keyMode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKeyMode(String value) {
        this.keyMode = value;
    }

    /**
     * Gets the value of the languageDirection property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLanguageDirection() {
        return languageDirection;
    }

    /**
     * Sets the value of the languageDirection property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLanguageDirection(String value) {
        this.languageDirection = value;
    }

    /**
     * Gets the value of the lockMode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLockMode() {
        return lockMode;
    }

    /**
     * Sets the value of the lockMode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLockMode(String value) {
        this.lockMode = value;
    }

    /**
     * Gets the value of the maximumQueryTime property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getMaximumQueryTime() {
        return maximumQueryTime;
    }

    /**
     * Sets the value of the maximumQueryTime property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setMaximumQueryTime(BigInteger value) {
        this.maximumQueryTime = value;
    }

    /**
     * Gets the value of the maximumRecordsFetched property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getMaximumRecordsFetched() {
        return maximumRecordsFetched;
    }

    /**
     * Sets the value of the maximumRecordsFetched property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setMaximumRecordsFetched(BigInteger value) {
        this.maximumRecordsFetched = value;
    }

    /**
     * Gets the value of the navigationStyle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNavigationStyle() {
        return navigationStyle;
    }

    /**
     * Sets the value of the navigationStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNavigationStyle(String value) {
        this.navigationStyle = value;
    }

    /**
     * Gets the value of the parentModuleType property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getParentModuleType() {
        return parentModuleType;
    }

    /**
     * Sets the value of the parentModuleType property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setParentModuleType(BigInteger value) {
        this.parentModuleType = value;
    }

    /**
     * Gets the value of the parentType property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getParentType() {
        return parentType;
    }

    /**
     * Sets the value of the parentType property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setParentType(BigInteger value) {
        this.parentType = value;
    }

    /**
     * Gets the value of the persistentClientInfoLength property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getPersistentClientInfoLength() {
        return persistentClientInfoLength;
    }

    /**
     * Sets the value of the persistentClientInfoLength property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setPersistentClientInfoLength(BigInteger value) {
        this.persistentClientInfoLength = value;
    }

    /**
     * Gets the value of the queryDataSourceType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getQueryDataSourceType() {
        return queryDataSourceType;
    }

    /**
     * Sets the value of the queryDataSourceType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setQueryDataSourceType(String value) {
        this.queryDataSourceType = value;
    }

    /**
     * Gets the value of the recordOrientation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRecordOrientation() {
        return recordOrientation;
    }

    /**
     * Sets the value of the recordOrientation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRecordOrientation(String value) {
        this.recordOrientation = value;
    }

    /**
     * Gets the value of the recordsBufferedCount property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getRecordsBufferedCount() {
        return recordsBufferedCount;
    }

    /**
     * Sets the value of the recordsBufferedCount property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setRecordsBufferedCount(BigInteger value) {
        this.recordsBufferedCount = value;
    }

    /**
     * Gets the value of the recordsDisplayCount property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getRecordsDisplayCount() {
        return recordsDisplayCount;
    }

    /**
     * Sets the value of the recordsDisplayCount property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setRecordsDisplayCount(BigInteger value) {
        this.recordsDisplayCount = value;
    }

    /**
     * Gets the value of the recordsFetchedCount property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getRecordsFetchedCount() {
        return recordsFetchedCount;
    }

    /**
     * Sets the value of the recordsFetchedCount property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setRecordsFetchedCount(BigInteger value) {
        this.recordsFetchedCount = value;
    }

    /**
     * Gets the value of the scrollbarLength property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getScrollbarLength() {
        return scrollbarLength;
    }

    /**
     * Sets the value of the scrollbarLength property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setScrollbarLength(BigInteger value) {
        this.scrollbarLength = value;
    }

    /**
     * Gets the value of the scrollbarOrientation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getScrollbarOrientation() {
        return scrollbarOrientation;
    }

    /**
     * Sets the value of the scrollbarOrientation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setScrollbarOrientation(String value) {
        this.scrollbarOrientation = value;
    }

    /**
     * Gets the value of the scrollbarWidth property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getScrollbarWidth() {
        return scrollbarWidth;
    }

    /**
     * Sets the value of the scrollbarWidth property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setScrollbarWidth(BigInteger value) {
        this.scrollbarWidth = value;
    }

    /**
     * Gets the value of the scrollbarXPosition property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getScrollbarXPosition() {
        return scrollbarXPosition;
    }

    /**
     * Sets the value of the scrollbarXPosition property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setScrollbarXPosition(BigInteger value) {
        this.scrollbarXPosition = value;
    }

    /**
     * Gets the value of the scrollbarYPosition property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getScrollbarYPosition() {
        return scrollbarYPosition;
    }

    /**
     * Sets the value of the scrollbarYPosition property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setScrollbarYPosition(BigInteger value) {
        this.scrollbarYPosition = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

    /**
     * Gets the value of the backColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackColor() {
        return backColor;
    }

    /**
     * Sets the value of the backColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackColor(String value) {
        this.backColor = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the deleteProcedureName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeleteProcedureName() {
        return deleteProcedureName;
    }

    /**
     * Sets the value of the deleteProcedureName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeleteProcedureName(String value) {
        this.deleteProcedureName = value;
    }

    /**
     * Gets the value of the dmlDataName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDMLDataName() {
        return dmlDataName;
    }

    /**
     * Sets the value of the dmlDataName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDMLDataName(String value) {
        this.dmlDataName = value;
    }

    /**
     * Gets the value of the fillPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillPattern() {
        return fillPattern;
    }

    /**
     * Sets the value of the fillPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillPattern(String value) {
        this.fillPattern = value;
    }

    /**
     * Gets the value of the foregroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForegroundColor() {
        return foregroundColor;
    }

    /**
     * Sets the value of the foregroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForegroundColor(String value) {
        this.foregroundColor = value;
    }

    /**
     * Gets the value of the insertProcedureName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsertProcedureName() {
        return insertProcedureName;
    }

    /**
     * Sets the value of the insertProcedureName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsertProcedureName(String value) {
        this.insertProcedureName = value;
    }

    /**
     * Gets the value of the lockProcedureName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLockProcedureName() {
        return lockProcedureName;
    }

    /**
     * Sets the value of the lockProcedureName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLockProcedureName(String value) {
        this.lockProcedureName = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nextNavigationBlockName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextNavigationBlockName() {
        return nextNavigationBlockName;
    }

    /**
     * Sets the value of the nextNavigationBlockName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextNavigationBlockName(String value) {
        this.nextNavigationBlockName = value;
    }

    /**
     * Gets the value of the optionHint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionHint() {
        return optionHint;
    }

    /**
     * Sets the value of the optionHint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionHint(String value) {
        this.optionHint = value;
    }

    /**
     * Gets the value of the orderByClause property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Sets the value of the orderByClause property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderByClause(String value) {
        this.orderByClause = value;
    }

    /**
     * Gets the value of the parentFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentFilename() {
        return parentFilename;
    }

    /**
     * Sets the value of the parentFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentFilename(String value) {
        this.parentFilename = value;
    }

    /**
     * Gets the value of the parentFilepath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentFilepath() {
        return parentFilepath;
    }

    /**
     * Sets the value of the parentFilepath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentFilepath(String value) {
        this.parentFilepath = value;
    }

    /**
     * Gets the value of the parentModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentModule() {
        return parentModule;
    }

    /**
     * Sets the value of the parentModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentModule(String value) {
        this.parentModule = value;
    }

    /**
     * Gets the value of the parentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * Sets the value of the parentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentName(String value) {
        this.parentName = value;
    }

    /**
     * Gets the value of the previousNavigationBlockName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousNavigationBlockName() {
        return previousNavigationBlockName;
    }

    /**
     * Sets the value of the previousNavigationBlockName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousNavigationBlockName(String value) {
        this.previousNavigationBlockName = value;
    }

    /**
     * Gets the value of the queryDataSourceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryDataSourceName() {
        return queryDataSourceName;
    }

    /**
     * Sets the value of the queryDataSourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryDataSourceName(String value) {
        this.queryDataSourceName = value;
    }

    /**
     * Gets the value of the recordVisualAttributeGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordVisualAttributeGroupName() {
        return recordVisualAttributeGroupName;
    }

    /**
     * Sets the value of the recordVisualAttributeGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordVisualAttributeGroupName(String value) {
        this.recordVisualAttributeGroupName = value;
    }

    /**
     * Gets the value of the scrollbarCanvasName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScrollbarCanvasName() {
        return scrollbarCanvasName;
    }

    /**
     * Sets the value of the scrollbarCanvasName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScrollbarCanvasName(String value) {
        this.scrollbarCanvasName = value;
    }

    /**
     * Gets the value of the scrollbarTabPageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScrollbarTabPageName() {
        return scrollbarTabPageName;
    }

    /**
     * Sets the value of the scrollbarTabPageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScrollbarTabPageName(String value) {
        this.scrollbarTabPageName = value;
    }

    /**
     * Gets the value of the updateProcedureName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateProcedureName() {
        return updateProcedureName;
    }

    /**
     * Sets the value of the updateProcedureName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateProcedureName(String value) {
        this.updateProcedureName = value;
    }

    /**
     * Gets the value of the visualAttributeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisualAttributeName() {
        return visualAttributeName;
    }

    /**
     * Sets the value of the visualAttributeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisualAttributeName(String value) {
        this.visualAttributeName = value;
    }

    /**
     * Gets the value of the whereClause property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhereClause() {
        return whereClause;
    }

    /**
     * Sets the value of the whereClause property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhereClause(String value) {
        this.whereClause = value;
    }

    /**
     * Gets the value of the smartClass property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSmartClass() {
        return smartClass;
    }

    /**
     * Sets the value of the smartClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSmartClass(Boolean value) {
        this.smartClass = value;
    }


    public int getNumberOfTriggers() {
        return numberOfTriggers;
    }

    public void setNumberOfTriggers(int numberOfTriggers) {
        this.numberOfTriggers = numberOfTriggers;
    }
}
