//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 09:54:43 PM CET 
//


package com.mobissime.forms.objects;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Canvas complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Canvas">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}Graphics" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}TabPage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}VisualState" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="DirtyInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DisplayViewport" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="RaiseOnEnter" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ShowHorizontalScrollbar" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ShowVerticalScrollbar" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="SubclassObjectGroup" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Bevel" type="{http://xmlns.oracle.com/Forms}BevelType" />
 *       &lt;attribute name="CanvasType" type="{http://xmlns.oracle.com/Forms}CanvasTypeType" />
 *       &lt;attribute name="FontSize" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FontSpacing" type="{http://xmlns.oracle.com/Forms}FontSpacingType" />
 *       &lt;attribute name="FontStyle" type="{http://xmlns.oracle.com/Forms}FontStyleType" />
 *       &lt;attribute name="FontWeight" type="{http://xmlns.oracle.com/Forms}FontWeightType" />
 *       &lt;attribute name="Height" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="LanguageDirection" type="{http://xmlns.oracle.com/Forms}LanguageDirectionType" />
 *       &lt;attribute name="ParentModuleType" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ParentType" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="PersistentClientInfoLength" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="TabActionStyle" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="TabAttachmentEdge" type="{http://xmlns.oracle.com/Forms}TabAttachmentEdgeType" />
 *       &lt;attribute name="TabStyle" type="{http://xmlns.oracle.com/Forms}TabStyleType" />
 *       &lt;attribute name="TabWidthStyle" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ViewportHeight" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ViewportWidth" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ViewportXPosition" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ViewportXPositionOnCanvas" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ViewportYPosition" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ViewportYPositionOnCanvas" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Width" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="BackColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FillPattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FontName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ForegroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="HelpBookTopic" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" use="required" type="{http://xmlns.oracle.com/Forms}nameType" />
 *       &lt;attribute name="ParentFilename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentFilepath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentModule" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PopupMenuName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="VisualAttributeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="WindowName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SmartClass" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Canvas", propOrder = {
    "graphicsOrTabPageOrVisualState"
})
public class Canvas {

    @XmlElements({
        @XmlElement(name = "Graphics", type = Graphics.class),
        @XmlElement(name = "TabPage", type = TabPage.class),
        @XmlElement(name = "VisualState", type = VisualState.class)
    })
    protected List<Object> graphicsOrTabPageOrVisualState;
    @XmlAttribute(name = "DirtyInfo")
    protected Boolean dirtyInfo;
    @XmlAttribute(name = "DisplayViewport")
    protected Boolean displayViewport;
    @XmlAttribute(name = "RaiseOnEnter")
    protected Boolean raiseOnEnter;
    @XmlAttribute(name = "ShowHorizontalScrollbar")
    protected Boolean showHorizontalScrollbar;
    @XmlAttribute(name = "ShowVerticalScrollbar")
    protected Boolean showVerticalScrollbar;
    @XmlAttribute(name = "SubclassObjectGroup")
    protected Boolean subclassObjectGroup;
    @XmlAttribute(name = "Visible")
    protected Boolean visible;
    @XmlAttribute(name = "Bevel")
    protected String bevel;
    @XmlAttribute(name = "CanvasType")
    protected String canvasType;
    @XmlAttribute(name = "FontSize")
    protected BigInteger fontSize;
    @XmlAttribute(name = "FontSpacing")
    protected String fontSpacing;
    @XmlAttribute(name = "FontStyle")
    protected String fontStyle;
    @XmlAttribute(name = "FontWeight")
    protected String fontWeight;
    @XmlAttribute(name = "Height")
    protected BigInteger height;
    @XmlAttribute(name = "LanguageDirection")
    protected String languageDirection;
    @XmlAttribute(name = "ParentModuleType")
    protected BigInteger parentModuleType;
    @XmlAttribute(name = "ParentType")
    protected BigInteger parentType;
    @XmlAttribute(name = "PersistentClientInfoLength")
    protected BigInteger persistentClientInfoLength;
    @XmlAttribute(name = "TabActionStyle")
    protected BigInteger tabActionStyle;
    @XmlAttribute(name = "TabAttachmentEdge")
    protected String tabAttachmentEdge;
    @XmlAttribute(name = "TabStyle")
    protected String tabStyle;
    @XmlAttribute(name = "TabWidthStyle")
    protected BigInteger tabWidthStyle;
    @XmlAttribute(name = "ViewportHeight")
    protected BigInteger viewportHeight;
    @XmlAttribute(name = "ViewportWidth")
    protected BigInteger viewportWidth;
    @XmlAttribute(name = "ViewportXPosition")
    protected BigInteger viewportXPosition;
    @XmlAttribute(name = "ViewportXPositionOnCanvas")
    protected BigInteger viewportXPositionOnCanvas;
    @XmlAttribute(name = "ViewportYPosition")
    protected BigInteger viewportYPosition;
    @XmlAttribute(name = "ViewportYPositionOnCanvas")
    protected BigInteger viewportYPositionOnCanvas;
    @XmlAttribute(name = "Width")
    protected BigInteger width;
    @XmlAttribute(name = "BackColor")
    protected String backColor;
    @XmlAttribute(name = "Comment")
    protected String comment;
    @XmlAttribute(name = "FillPattern")
    protected String fillPattern;
    @XmlAttribute(name = "FontName")
    protected String fontName;
    @XmlAttribute(name = "ForegroundColor")
    protected String foregroundColor;
    @XmlAttribute(name = "HelpBookTopic")
    protected String helpBookTopic;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "ParentFilename")
    protected String parentFilename;
    @XmlAttribute(name = "ParentFilepath")
    protected String parentFilepath;
    @XmlAttribute(name = "ParentModule")
    protected String parentModule;
    @XmlAttribute(name = "ParentName")
    protected String parentName;
    @XmlAttribute(name = "PopupMenuName")
    protected String popupMenuName;
    @XmlAttribute(name = "VisualAttributeName")
    protected String visualAttributeName;
    @XmlAttribute(name = "WindowName")
    protected String windowName;
    @XmlAttribute(name = "SmartClass")
    protected Boolean smartClass;

    /**
     * Gets the value of the graphicsOrTabPageOrVisualState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the graphicsOrTabPageOrVisualState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGraphicsOrTabPageOrVisualState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Graphics }
     * {@link TabPage }
     * {@link VisualState }
     * 
     * 
     */
    public List<Object> getGraphicsOrTabPageOrVisualState() {
        if (graphicsOrTabPageOrVisualState == null) {
            graphicsOrTabPageOrVisualState = new ArrayList<Object>();
        }
        return this.graphicsOrTabPageOrVisualState;
    }

    /**
     * Gets the value of the dirtyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDirtyInfo() {
        return dirtyInfo;
    }

    /**
     * Sets the value of the dirtyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDirtyInfo(Boolean value) {
        this.dirtyInfo = value;
    }

    /**
     * Gets the value of the displayViewport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisplayViewport() {
        return displayViewport;
    }

    /**
     * Sets the value of the displayViewport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisplayViewport(Boolean value) {
        this.displayViewport = value;
    }

    /**
     * Gets the value of the raiseOnEnter property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRaiseOnEnter() {
        return raiseOnEnter;
    }

    /**
     * Sets the value of the raiseOnEnter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRaiseOnEnter(Boolean value) {
        this.raiseOnEnter = value;
    }

    /**
     * Gets the value of the showHorizontalScrollbar property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowHorizontalScrollbar() {
        return showHorizontalScrollbar;
    }

    /**
     * Sets the value of the showHorizontalScrollbar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowHorizontalScrollbar(Boolean value) {
        this.showHorizontalScrollbar = value;
    }

    /**
     * Gets the value of the showVerticalScrollbar property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowVerticalScrollbar() {
        return showVerticalScrollbar;
    }

    /**
     * Sets the value of the showVerticalScrollbar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowVerticalScrollbar(Boolean value) {
        this.showVerticalScrollbar = value;
    }

    /**
     * Gets the value of the subclassObjectGroup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSubclassObjectGroup() {
        return subclassObjectGroup;
    }

    /**
     * Sets the value of the subclassObjectGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSubclassObjectGroup(Boolean value) {
        this.subclassObjectGroup = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisible(Boolean value) {
        this.visible = value;
    }

    /**
     * Gets the value of the bevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBevel() {
        return bevel;
    }

    /**
     * Sets the value of the bevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBevel(String value) {
        this.bevel = value;
    }

    /**
     * Gets the value of the canvasType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanvasType() {
        return canvasType;
    }

    /**
     * Sets the value of the canvasType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanvasType(String value) {
        this.canvasType = value;
    }

    /**
     * Gets the value of the fontSize property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getFontSize() {
        return fontSize;
    }

    /**
     * Sets the value of the fontSize property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setFontSize(BigInteger value) {
        this.fontSize = value;
    }

    /**
     * Gets the value of the fontSpacing property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFontSpacing() {
        return fontSpacing;
    }

    /**
     * Sets the value of the fontSpacing property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFontSpacing(String value) {
        this.fontSpacing = value;
    }

    /**
     * Gets the value of the fontStyle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFontStyle() {
        return fontStyle;
    }

    /**
     * Sets the value of the fontStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFontStyle(String value) {
        this.fontStyle = value;
    }

    /**
     * Gets the value of the fontWeight property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFontWeight() {
        return fontWeight;
    }

    /**
     * Sets the value of the fontWeight property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFontWeight(String value) {
        this.fontWeight = value;
    }

    /**
     * Gets the value of the height property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setHeight(BigInteger value) {
        this.height = value;
    }

    /**
     * Gets the value of the languageDirection property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLanguageDirection() {
        return languageDirection;
    }

    /**
     * Sets the value of the languageDirection property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLanguageDirection(String value) {
        this.languageDirection = value;
    }

    /**
     * Gets the value of the parentModuleType property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getParentModuleType() {
        return parentModuleType;
    }

    /**
     * Sets the value of the parentModuleType property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setParentModuleType(BigInteger value) {
        this.parentModuleType = value;
    }

    /**
     * Gets the value of the parentType property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getParentType() {
        return parentType;
    }

    /**
     * Sets the value of the parentType property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setParentType(BigInteger value) {
        this.parentType = value;
    }

    /**
     * Gets the value of the persistentClientInfoLength property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getPersistentClientInfoLength() {
        return persistentClientInfoLength;
    }

    /**
     * Sets the value of the persistentClientInfoLength property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setPersistentClientInfoLength(BigInteger value) {
        this.persistentClientInfoLength = value;
    }

    /**
     * Gets the value of the tabActionStyle property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getTabActionStyle() {
        return tabActionStyle;
    }

    /**
     * Sets the value of the tabActionStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setTabActionStyle(BigInteger value) {
        this.tabActionStyle = value;
    }

    /**
     * Gets the value of the tabAttachmentEdge property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTabAttachmentEdge() {
        return tabAttachmentEdge;
    }

    /**
     * Sets the value of the tabAttachmentEdge property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTabAttachmentEdge(String value) {
        this.tabAttachmentEdge = value;
    }

    /**
     * Gets the value of the tabStyle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTabStyle() {
        return tabStyle;
    }

    /**
     * Sets the value of the tabStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTabStyle(String value) {
        this.tabStyle = value;
    }

    /**
     * Gets the value of the tabWidthStyle property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getTabWidthStyle() {
        return tabWidthStyle;
    }

    /**
     * Sets the value of the tabWidthStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setTabWidthStyle(BigInteger value) {
        this.tabWidthStyle = value;
    }

    /**
     * Gets the value of the viewportHeight property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getViewportHeight() {
        return viewportHeight;
    }

    /**
     * Sets the value of the viewportHeight property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setViewportHeight(BigInteger value) {
        this.viewportHeight = value;
    }

    /**
     * Gets the value of the viewportWidth property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getViewportWidth() {
        return viewportWidth;
    }

    /**
     * Sets the value of the viewportWidth property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setViewportWidth(BigInteger value) {
        this.viewportWidth = value;
    }

    /**
     * Gets the value of the viewportXPosition property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getViewportXPosition() {
        return viewportXPosition;
    }

    /**
     * Sets the value of the viewportXPosition property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setViewportXPosition(BigInteger value) {
        this.viewportXPosition = value;
    }

    /**
     * Gets the value of the viewportXPositionOnCanvas property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getViewportXPositionOnCanvas() {
        return viewportXPositionOnCanvas;
    }

    /**
     * Sets the value of the viewportXPositionOnCanvas property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setViewportXPositionOnCanvas(BigInteger value) {
        this.viewportXPositionOnCanvas = value;
    }

    /**
     * Gets the value of the viewportYPosition property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getViewportYPosition() {
        return viewportYPosition;
    }

    /**
     * Sets the value of the viewportYPosition property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setViewportYPosition(BigInteger value) {
        this.viewportYPosition = value;
    }

    /**
     * Gets the value of the viewportYPositionOnCanvas property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getViewportYPositionOnCanvas() {
        return viewportYPositionOnCanvas;
    }

    /**
     * Sets the value of the viewportYPositionOnCanvas property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setViewportYPositionOnCanvas(BigInteger value) {
        this.viewportYPositionOnCanvas = value;
    }

    /**
     * Gets the value of the width property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setWidth(BigInteger value) {
        this.width = value;
    }

    /**
     * Gets the value of the backColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackColor() {
        return backColor;
    }

    /**
     * Sets the value of the backColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackColor(String value) {
        this.backColor = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the fillPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillPattern() {
        return fillPattern;
    }

    /**
     * Sets the value of the fillPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillPattern(String value) {
        this.fillPattern = value;
    }

    /**
     * Gets the value of the fontName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontName() {
        return fontName;
    }

    /**
     * Sets the value of the fontName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontName(String value) {
        this.fontName = value;
    }

    /**
     * Gets the value of the foregroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForegroundColor() {
        return foregroundColor;
    }

    /**
     * Sets the value of the foregroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForegroundColor(String value) {
        this.foregroundColor = value;
    }

    /**
     * Gets the value of the helpBookTopic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelpBookTopic() {
        return helpBookTopic;
    }

    /**
     * Sets the value of the helpBookTopic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelpBookTopic(String value) {
        this.helpBookTopic = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the parentFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentFilename() {
        return parentFilename;
    }

    /**
     * Sets the value of the parentFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentFilename(String value) {
        this.parentFilename = value;
    }

    /**
     * Gets the value of the parentFilepath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentFilepath() {
        return parentFilepath;
    }

    /**
     * Sets the value of the parentFilepath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentFilepath(String value) {
        this.parentFilepath = value;
    }

    /**
     * Gets the value of the parentModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentModule() {
        return parentModule;
    }

    /**
     * Sets the value of the parentModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentModule(String value) {
        this.parentModule = value;
    }

    /**
     * Gets the value of the parentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * Sets the value of the parentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentName(String value) {
        this.parentName = value;
    }

    /**
     * Gets the value of the popupMenuName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPopupMenuName() {
        return popupMenuName;
    }

    /**
     * Sets the value of the popupMenuName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPopupMenuName(String value) {
        this.popupMenuName = value;
    }

    /**
     * Gets the value of the visualAttributeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisualAttributeName() {
        return visualAttributeName;
    }

    /**
     * Sets the value of the visualAttributeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisualAttributeName(String value) {
        this.visualAttributeName = value;
    }

    /**
     * Gets the value of the windowName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWindowName() {
        return windowName;
    }

    /**
     * Sets the value of the windowName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWindowName(String value) {
        this.windowName = value;
    }

    /**
     * Gets the value of the smartClass property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSmartClass() {
        return smartClass;
    }

    /**
     * Sets the value of the smartClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSmartClass(Boolean value) {
        this.smartClass = value;
    }

}
