//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 09:54:43 PM CET 
//


package com.mobissime.forms.objects;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Graphics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Graphics">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}CompoundText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}Graphics" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}Point" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="AllowExpansion" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="AllowMultiLinePrompts" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="AllowStartAttachmentPrompts" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="AllowTopAttachmentPrompts" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="BoundingBoxScalable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Closed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DirtyInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Dither" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="FixedBoundingBox" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="FontScaleable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ShowScrollbar" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Shrinkwrap" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="SubclassSubObject" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="VerticalFill" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="WrapText" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ArrowStyle" type="{http://xmlns.oracle.com/Forms}ArrowStyleType" />
 *       &lt;attribute name="Bevel" type="{http://xmlns.oracle.com/Forms}BevelType" />
 *       &lt;attribute name="CapStyle" type="{http://xmlns.oracle.com/Forms}CapStyleType" />
 *       &lt;attribute name="ClipHeight" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ClipWidth" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ClipXPosition" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ClipYPosition" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="CornerRadiusX" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="CornerRadiusY" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="CustomSpacing" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="DashStyle" type="{http://xmlns.oracle.com/Forms}DashStyleType" />
 *       &lt;attribute name="DisplayQuality" type="{http://xmlns.oracle.com/Forms}DisplayQualityType" />
 *       &lt;attribute name="DistanceBetweenRecords" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FrameAlign" type="{http://xmlns.oracle.com/Forms}FrameAlignType" />
 *       &lt;attribute name="FrameTitleAlign" type="{http://xmlns.oracle.com/Forms}FrameTitleAlignType" />
 *       &lt;attribute name="FrameTitleFontSize" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FrameTitleFontSpacing" type="{http://xmlns.oracle.com/Forms}FrameTitleFontSpacingType" />
 *       &lt;attribute name="FrameTitleFontStyle" type="{http://xmlns.oracle.com/Forms}FrameTitleFontStyleType" />
 *       &lt;attribute name="FrameTitleFontWeight" type="{http://xmlns.oracle.com/Forms}FrameTitleFontWeightType" />
 *       &lt;attribute name="FrameTitleOffset" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FrameTitleSpacing" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="GraphicsFontColorCode" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="GraphicsFontSize" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="GraphicsFontSpacing" type="{http://xmlns.oracle.com/Forms}GraphicsFontSpacingType" />
 *       &lt;attribute name="GraphicsFontStyle" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="GraphicsFontWeight" type="{http://xmlns.oracle.com/Forms}GraphicsFontWeightType" />
 *       &lt;attribute name="GraphicsType" type="{http://xmlns.oracle.com/Forms}GraphicsTypeType" />
 *       &lt;attribute name="Height" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="HorizontalJustification" type="{http://xmlns.oracle.com/Forms}HorizontalJustificationType" />
 *       &lt;attribute name="HorizontalMargin" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="HorizontalObjectOffset" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="HorizontalOrigin" type="{http://xmlns.oracle.com/Forms}HorizontalOriginType" />
 *       &lt;attribute name="ImageDepth" type="{http://xmlns.oracle.com/Forms}ImageDepthType" />
 *       &lt;attribute name="ImageFormat" type="{http://xmlns.oracle.com/Forms}ImageFormatType" />
 *       &lt;attribute name="InternalEndAngle" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="InternalLineWidth" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="InternalRotationAngle" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="InternalStartAngle" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="JoinStyle" type="{http://xmlns.oracle.com/Forms}JoinStyleType" />
 *       &lt;attribute name="LanguageDirection" type="{http://xmlns.oracle.com/Forms}LanguageDirectionType" />
 *       &lt;attribute name="LayoutStyle" type="{http://xmlns.oracle.com/Forms}LayoutStyleType" />
 *       &lt;attribute name="LineSpacing" type="{http://xmlns.oracle.com/Forms}LineSpacingType" />
 *       &lt;attribute name="MaximumObjs" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ParentModuleType" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ParentType" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="PersistentClientInfoLength" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="RecordsDisplayCount" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ScrollbarAlign" type="{http://xmlns.oracle.com/Forms}ScrollbarAlignType" />
 *       &lt;attribute name="ScrollbarWidth" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SingleObjectAlign" type="{http://xmlns.oracle.com/Forms}SingleObjectAlignType" />
 *       &lt;attribute name="StartPromptAlign" type="{http://xmlns.oracle.com/Forms}StartPromptAlignType" />
 *       &lt;attribute name="StartPromptOffset" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="TopPromptAlign" type="{http://xmlns.oracle.com/Forms}TopPromptAlignType" />
 *       &lt;attribute name="TopPromptOffset" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="TitleReadingOrder" type="{http://xmlns.oracle.com/Forms}TitleReadingOrderType" />
 *       &lt;attribute name="UpdateLayout" type="{http://xmlns.oracle.com/Forms}UpdateLayoutType" />
 *       &lt;attribute name="VerticalJustification" type="{http://xmlns.oracle.com/Forms}VerticalJustificationType" />
 *       &lt;attribute name="VerticalMargin" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="VerticalObjectOffset" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="VerticalOrigin" type="{http://xmlns.oracle.com/Forms}VerticalOriginType" />
 *       &lt;attribute name="Width" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="XPosition" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="YPosition" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="BackColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EdgeBackColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EdgeForegroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EdgePattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FillPattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ForegroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FrameTitle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FrameTitleBackColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FrameTitleFillPattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FrameTitleFontName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FrameTitleForegroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FrameTitleVisualAttributeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="GraphicsFontColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="GraphicsFontName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="GraphicsText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LayoutDataBlockName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" use="required" type="{http://xmlns.oracle.com/Forms}nameType" />
 *       &lt;attribute name="ParentFilename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentFilepath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentModule" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TabPageName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="VisualAttributeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ImageFilename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SmartClass" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Graphics", propOrder = {
    "compoundTextOrGraphicsOrPoint"
})
public class Graphics {

    @XmlElements({
        @XmlElement(name = "CompoundText", type = CompoundText.class),
        @XmlElement(name = "Graphics", type = Graphics.class),
        @XmlElement(name = "Point", type = Point.class)
    })
    protected List<Object> compoundTextOrGraphicsOrPoint;
    @XmlAttribute(name = "AllowExpansion")
    protected Boolean allowExpansion;
    @XmlAttribute(name = "AllowMultiLinePrompts")
    protected Boolean allowMultiLinePrompts;
    @XmlAttribute(name = "AllowStartAttachmentPrompts")
    protected Boolean allowStartAttachmentPrompts;
    @XmlAttribute(name = "AllowTopAttachmentPrompts")
    protected Boolean allowTopAttachmentPrompts;
    @XmlAttribute(name = "BoundingBoxScalable")
    protected Boolean boundingBoxScalable;
    @XmlAttribute(name = "Closed")
    protected Boolean closed;
    @XmlAttribute(name = "DirtyInfo")
    protected Boolean dirtyInfo;
    @XmlAttribute(name = "Dither")
    protected Boolean dither;
    @XmlAttribute(name = "FixedBoundingBox")
    protected Boolean fixedBoundingBox;
    @XmlAttribute(name = "FontScaleable")
    protected Boolean fontScaleable;
    @XmlAttribute(name = "ShowScrollbar")
    protected Boolean showScrollbar;
    @XmlAttribute(name = "Shrinkwrap")
    protected Boolean shrinkwrap;
    @XmlAttribute(name = "SubclassSubObject")
    protected Boolean subclassSubObject;
    @XmlAttribute(name = "VerticalFill")
    protected Boolean verticalFill;
    @XmlAttribute(name = "WrapText")
    protected Boolean wrapText;
    @XmlAttribute(name = "ArrowStyle")
    protected String arrowStyle;
    @XmlAttribute(name = "Bevel")
    protected String bevel;
    @XmlAttribute(name = "CapStyle")
    protected String capStyle;
    @XmlAttribute(name = "ClipHeight")
    protected BigInteger clipHeight;
    @XmlAttribute(name = "ClipWidth")
    protected BigInteger clipWidth;
    @XmlAttribute(name = "ClipXPosition")
    protected BigInteger clipXPosition;
    @XmlAttribute(name = "ClipYPosition")
    protected BigInteger clipYPosition;
    @XmlAttribute(name = "CornerRadiusX")
    protected BigInteger cornerRadiusX;
    @XmlAttribute(name = "CornerRadiusY")
    protected BigInteger cornerRadiusY;
    @XmlAttribute(name = "CustomSpacing")
    protected BigInteger customSpacing;
    @XmlAttribute(name = "DashStyle")
    protected String dashStyle;
    @XmlAttribute(name = "DisplayQuality")
    protected String displayQuality;
    @XmlAttribute(name = "DistanceBetweenRecords")
    protected BigInteger distanceBetweenRecords;
    @XmlAttribute(name = "FrameAlign")
    protected String frameAlign;
    @XmlAttribute(name = "FrameTitleAlign")
    protected String frameTitleAlign;
    @XmlAttribute(name = "FrameTitleFontSize")
    protected BigInteger frameTitleFontSize;
    @XmlAttribute(name = "FrameTitleFontSpacing")
    protected String frameTitleFontSpacing;
    @XmlAttribute(name = "FrameTitleFontStyle")
    protected String frameTitleFontStyle;
    @XmlAttribute(name = "FrameTitleFontWeight")
    protected String frameTitleFontWeight;
    @XmlAttribute(name = "FrameTitleOffset")
    protected BigInteger frameTitleOffset;
    @XmlAttribute(name = "FrameTitleSpacing")
    protected BigInteger frameTitleSpacing;
    @XmlAttribute(name = "GraphicsFontColorCode")
    protected BigInteger graphicsFontColorCode;
    @XmlAttribute(name = "GraphicsFontSize")
    protected BigInteger graphicsFontSize;
    @XmlAttribute(name = "GraphicsFontSpacing")
    protected String graphicsFontSpacing;
    @XmlAttribute(name = "GraphicsFontStyle")
    protected BigInteger graphicsFontStyle;
    @XmlAttribute(name = "GraphicsFontWeight")
    protected String graphicsFontWeight;
    @XmlAttribute(name = "GraphicsType")
    protected String graphicsType;
    @XmlAttribute(name = "Height")
    protected BigInteger height;
    @XmlAttribute(name = "HorizontalJustification")
    protected String horizontalJustification;
    @XmlAttribute(name = "HorizontalMargin")
    protected BigInteger horizontalMargin;
    @XmlAttribute(name = "HorizontalObjectOffset")
    protected BigInteger horizontalObjectOffset;
    @XmlAttribute(name = "HorizontalOrigin")
    protected String horizontalOrigin;
    @XmlAttribute(name = "ImageDepth")
    protected String imageDepth;
    @XmlAttribute(name = "ImageFormat")
    protected String imageFormat;
    @XmlAttribute(name = "InternalEndAngle")
    protected BigInteger internalEndAngle;
    @XmlAttribute(name = "InternalLineWidth")
    protected BigInteger internalLineWidth;
    @XmlAttribute(name = "InternalRotationAngle")
    protected BigInteger internalRotationAngle;
    @XmlAttribute(name = "InternalStartAngle")
    protected BigInteger internalStartAngle;
    @XmlAttribute(name = "JoinStyle")
    protected String joinStyle;
    @XmlAttribute(name = "LanguageDirection")
    protected String languageDirection;
    @XmlAttribute(name = "LayoutStyle")
    protected String layoutStyle;
    @XmlAttribute(name = "LineSpacing")
    protected String lineSpacing;
    @XmlAttribute(name = "MaximumObjs")
    protected BigInteger maximumObjs;
    @XmlAttribute(name = "ParentModuleType")
    protected BigInteger parentModuleType;
    @XmlAttribute(name = "ParentType")
    protected BigInteger parentType;
    @XmlAttribute(name = "PersistentClientInfoLength")
    protected BigInteger persistentClientInfoLength;
    @XmlAttribute(name = "RecordsDisplayCount")
    protected BigInteger recordsDisplayCount;
    @XmlAttribute(name = "ScrollbarAlign")
    protected String scrollbarAlign;
    @XmlAttribute(name = "ScrollbarWidth")
    protected BigInteger scrollbarWidth;
    @XmlAttribute(name = "SingleObjectAlign")
    protected String singleObjectAlign;
    @XmlAttribute(name = "StartPromptAlign")
    protected String startPromptAlign;
    @XmlAttribute(name = "StartPromptOffset")
    protected BigInteger startPromptOffset;
    @XmlAttribute(name = "TopPromptAlign")
    protected String topPromptAlign;
    @XmlAttribute(name = "TopPromptOffset")
    protected BigInteger topPromptOffset;
    @XmlAttribute(name = "TitleReadingOrder")
    protected String titleReadingOrder;
    @XmlAttribute(name = "UpdateLayout")
    protected String updateLayout;
    @XmlAttribute(name = "VerticalJustification")
    protected String verticalJustification;
    @XmlAttribute(name = "VerticalMargin")
    protected BigInteger verticalMargin;
    @XmlAttribute(name = "VerticalObjectOffset")
    protected BigInteger verticalObjectOffset;
    @XmlAttribute(name = "VerticalOrigin")
    protected String verticalOrigin;
    @XmlAttribute(name = "Width")
    protected BigInteger width;
    @XmlAttribute(name = "XPosition")
    protected BigInteger xPosition;
    @XmlAttribute(name = "YPosition")
    protected BigInteger yPosition;
    @XmlAttribute(name = "BackColor")
    protected String backColor;
    @XmlAttribute(name = "EdgeBackColor")
    protected String edgeBackColor;
    @XmlAttribute(name = "EdgeForegroundColor")
    protected String edgeForegroundColor;
    @XmlAttribute(name = "EdgePattern")
    protected String edgePattern;
    @XmlAttribute(name = "FillPattern")
    protected String fillPattern;
    @XmlAttribute(name = "ForegroundColor")
    protected String foregroundColor;
    @XmlAttribute(name = "FrameTitle")
    protected String frameTitle;
    @XmlAttribute(name = "FrameTitleBackColor")
    protected String frameTitleBackColor;
    @XmlAttribute(name = "FrameTitleFillPattern")
    protected String frameTitleFillPattern;
    @XmlAttribute(name = "FrameTitleFontName")
    protected String frameTitleFontName;
    @XmlAttribute(name = "FrameTitleForegroundColor")
    protected String frameTitleForegroundColor;
    @XmlAttribute(name = "FrameTitleVisualAttributeName")
    protected String frameTitleVisualAttributeName;
    @XmlAttribute(name = "GraphicsFontColor")
    protected String graphicsFontColor;
    @XmlAttribute(name = "GraphicsFontName")
    protected String graphicsFontName;
    @XmlAttribute(name = "GraphicsText")
    protected String graphicsText;
    @XmlAttribute(name = "LayoutDataBlockName")
    protected String layoutDataBlockName;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "ParentFilename")
    protected String parentFilename;
    @XmlAttribute(name = "ParentFilepath")
    protected String parentFilepath;
    @XmlAttribute(name = "ParentModule")
    protected String parentModule;
    @XmlAttribute(name = "ParentName")
    protected String parentName;
    @XmlAttribute(name = "TabPageName")
    protected String tabPageName;
    @XmlAttribute(name = "VisualAttributeName")
    protected String visualAttributeName;
    @XmlAttribute(name = "ImageFilename")
    protected String imageFilename;
    @XmlAttribute(name = "SmartClass")
    protected Boolean smartClass;

    /**
     * Gets the value of the compoundTextOrGraphicsOrPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compoundTextOrGraphicsOrPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompoundTextOrGraphicsOrPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompoundText }
     * {@link Graphics }
     * {@link Point }
     *
     *
     */
    public List<Object> getCompoundTextOrGraphicsOrPoint() {
        if (compoundTextOrGraphicsOrPoint == null) {
            compoundTextOrGraphicsOrPoint = new ArrayList<Object>();
        }
        return this.compoundTextOrGraphicsOrPoint;
    }

    /**
     * Gets the value of the allowExpansion property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isAllowExpansion() {
        return allowExpansion;
    }

    /**
     * Sets the value of the allowExpansion property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setAllowExpansion(Boolean value) {
        this.allowExpansion = value;
    }

    /**
     * Gets the value of the allowMultiLinePrompts property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isAllowMultiLinePrompts() {
        return allowMultiLinePrompts;
    }

    /**
     * Sets the value of the allowMultiLinePrompts property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setAllowMultiLinePrompts(Boolean value) {
        this.allowMultiLinePrompts = value;
    }

    /**
     * Gets the value of the allowStartAttachmentPrompts property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isAllowStartAttachmentPrompts() {
        return allowStartAttachmentPrompts;
    }

    /**
     * Sets the value of the allowStartAttachmentPrompts property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setAllowStartAttachmentPrompts(Boolean value) {
        this.allowStartAttachmentPrompts = value;
    }

    /**
     * Gets the value of the allowTopAttachmentPrompts property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isAllowTopAttachmentPrompts() {
        return allowTopAttachmentPrompts;
    }

    /**
     * Sets the value of the allowTopAttachmentPrompts property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setAllowTopAttachmentPrompts(Boolean value) {
        this.allowTopAttachmentPrompts = value;
    }

    /**
     * Gets the value of the boundingBoxScalable property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isBoundingBoxScalable() {
        return boundingBoxScalable;
    }

    /**
     * Sets the value of the boundingBoxScalable property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setBoundingBoxScalable(Boolean value) {
        this.boundingBoxScalable = value;
    }

    /**
     * Gets the value of the closed property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isClosed() {
        return closed;
    }

    /**
     * Sets the value of the closed property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setClosed(Boolean value) {
        this.closed = value;
    }

    /**
     * Gets the value of the dirtyInfo property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isDirtyInfo() {
        return dirtyInfo;
    }

    /**
     * Sets the value of the dirtyInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setDirtyInfo(Boolean value) {
        this.dirtyInfo = value;
    }

    /**
     * Gets the value of the dither property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isDither() {
        return dither;
    }

    /**
     * Sets the value of the dither property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setDither(Boolean value) {
        this.dither = value;
    }

    /**
     * Gets the value of the fixedBoundingBox property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isFixedBoundingBox() {
        return fixedBoundingBox;
    }

    /**
     * Sets the value of the fixedBoundingBox property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setFixedBoundingBox(Boolean value) {
        this.fixedBoundingBox = value;
    }

    /**
     * Gets the value of the fontScaleable property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isFontScaleable() {
        return fontScaleable;
    }

    /**
     * Sets the value of the fontScaleable property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setFontScaleable(Boolean value) {
        this.fontScaleable = value;
    }

    /**
     * Gets the value of the showScrollbar property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isShowScrollbar() {
        return showScrollbar;
    }

    /**
     * Sets the value of the showScrollbar property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setShowScrollbar(Boolean value) {
        this.showScrollbar = value;
    }

    /**
     * Gets the value of the shrinkwrap property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isShrinkwrap() {
        return shrinkwrap;
    }

    /**
     * Sets the value of the shrinkwrap property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setShrinkwrap(Boolean value) {
        this.shrinkwrap = value;
    }

    /**
     * Gets the value of the subclassSubObject property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isSubclassSubObject() {
        return subclassSubObject;
    }

    /**
     * Sets the value of the subclassSubObject property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setSubclassSubObject(Boolean value) {
        this.subclassSubObject = value;
    }

    /**
     * Gets the value of the verticalFill property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isVerticalFill() {
        return verticalFill;
    }

    /**
     * Sets the value of the verticalFill property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setVerticalFill(Boolean value) {
        this.verticalFill = value;
    }

    /**
     * Gets the value of the wrapText property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isWrapText() {
        return wrapText;
    }

    /**
     * Sets the value of the wrapText property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setWrapText(Boolean value) {
        this.wrapText = value;
    }

    /**
     * Gets the value of the arrowStyle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getArrowStyle() {
        return arrowStyle;
    }

    /**
     * Sets the value of the arrowStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setArrowStyle(String value) {
        this.arrowStyle = value;
    }

    /**
     * Gets the value of the bevel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBevel() {
        return bevel;
    }

    /**
     * Sets the value of the bevel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBevel(String value) {
        this.bevel = value;
    }

    /**
     * Gets the value of the capStyle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCapStyle() {
        return capStyle;
    }

    /**
     * Sets the value of the capStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCapStyle(String value) {
        this.capStyle = value;
    }

    /**
     * Gets the value of the clipHeight property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getClipHeight() {
        return clipHeight;
    }

    /**
     * Sets the value of the clipHeight property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setClipHeight(BigInteger value) {
        this.clipHeight = value;
    }

    /**
     * Gets the value of the clipWidth property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getClipWidth() {
        return clipWidth;
    }

    /**
     * Sets the value of the clipWidth property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setClipWidth(BigInteger value) {
        this.clipWidth = value;
    }

    /**
     * Gets the value of the clipXPosition property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getClipXPosition() {
        return clipXPosition;
    }

    /**
     * Sets the value of the clipXPosition property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setClipXPosition(BigInteger value) {
        this.clipXPosition = value;
    }

    /**
     * Gets the value of the clipYPosition property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getClipYPosition() {
        return clipYPosition;
    }

    /**
     * Sets the value of the clipYPosition property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setClipYPosition(BigInteger value) {
        this.clipYPosition = value;
    }

    /**
     * Gets the value of the cornerRadiusX property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getCornerRadiusX() {
        return cornerRadiusX;
    }

    /**
     * Sets the value of the cornerRadiusX property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setCornerRadiusX(BigInteger value) {
        this.cornerRadiusX = value;
    }

    /**
     * Gets the value of the cornerRadiusY property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getCornerRadiusY() {
        return cornerRadiusY;
    }

    /**
     * Sets the value of the cornerRadiusY property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setCornerRadiusY(BigInteger value) {
        this.cornerRadiusY = value;
    }

    /**
     * Gets the value of the customSpacing property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getCustomSpacing() {
        return customSpacing;
    }

    /**
     * Sets the value of the customSpacing property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setCustomSpacing(BigInteger value) {
        this.customSpacing = value;
    }

    /**
     * Gets the value of the dashStyle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDashStyle() {
        return dashStyle;
    }

    /**
     * Sets the value of the dashStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDashStyle(String value) {
        this.dashStyle = value;
    }

    /**
     * Gets the value of the displayQuality property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDisplayQuality() {
        return displayQuality;
    }

    /**
     * Sets the value of the displayQuality property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDisplayQuality(String value) {
        this.displayQuality = value;
    }

    /**
     * Gets the value of the distanceBetweenRecords property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getDistanceBetweenRecords() {
        return distanceBetweenRecords;
    }

    /**
     * Sets the value of the distanceBetweenRecords property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setDistanceBetweenRecords(BigInteger value) {
        this.distanceBetweenRecords = value;
    }

    /**
     * Gets the value of the frameAlign property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFrameAlign() {
        return frameAlign;
    }

    /**
     * Sets the value of the frameAlign property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFrameAlign(String value) {
        this.frameAlign = value;
    }

    /**
     * Gets the value of the frameTitleAlign property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFrameTitleAlign() {
        return frameTitleAlign;
    }

    /**
     * Sets the value of the frameTitleAlign property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFrameTitleAlign(String value) {
        this.frameTitleAlign = value;
    }

    /**
     * Gets the value of the frameTitleFontSize property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getFrameTitleFontSize() {
        return frameTitleFontSize;
    }

    /**
     * Sets the value of the frameTitleFontSize property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setFrameTitleFontSize(BigInteger value) {
        this.frameTitleFontSize = value;
    }

    /**
     * Gets the value of the frameTitleFontSpacing property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFrameTitleFontSpacing() {
        return frameTitleFontSpacing;
    }

    /**
     * Sets the value of the frameTitleFontSpacing property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFrameTitleFontSpacing(String value) {
        this.frameTitleFontSpacing = value;
    }

    /**
     * Gets the value of the frameTitleFontStyle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFrameTitleFontStyle() {
        return frameTitleFontStyle;
    }

    /**
     * Sets the value of the frameTitleFontStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFrameTitleFontStyle(String value) {
        this.frameTitleFontStyle = value;
    }

    /**
     * Gets the value of the frameTitleFontWeight property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFrameTitleFontWeight() {
        return frameTitleFontWeight;
    }

    /**
     * Sets the value of the frameTitleFontWeight property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFrameTitleFontWeight(String value) {
        this.frameTitleFontWeight = value;
    }

    /**
     * Gets the value of the frameTitleOffset property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getFrameTitleOffset() {
        return frameTitleOffset;
    }

    /**
     * Sets the value of the frameTitleOffset property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setFrameTitleOffset(BigInteger value) {
        this.frameTitleOffset = value;
    }

    /**
     * Gets the value of the frameTitleSpacing property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getFrameTitleSpacing() {
        return frameTitleSpacing;
    }

    /**
     * Sets the value of the frameTitleSpacing property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setFrameTitleSpacing(BigInteger value) {
        this.frameTitleSpacing = value;
    }

    /**
     * Gets the value of the graphicsFontColorCode property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getGraphicsFontColorCode() {
        return graphicsFontColorCode;
    }

    /**
     * Sets the value of the graphicsFontColorCode property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setGraphicsFontColorCode(BigInteger value) {
        this.graphicsFontColorCode = value;
    }

    /**
     * Gets the value of the graphicsFontSize property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getGraphicsFontSize() {
        return graphicsFontSize;
    }

    /**
     * Sets the value of the graphicsFontSize property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setGraphicsFontSize(BigInteger value) {
        this.graphicsFontSize = value;
    }

    /**
     * Gets the value of the graphicsFontSpacing property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGraphicsFontSpacing() {
        return graphicsFontSpacing;
    }

    /**
     * Sets the value of the graphicsFontSpacing property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGraphicsFontSpacing(String value) {
        this.graphicsFontSpacing = value;
    }

    /**
     * Gets the value of the graphicsFontStyle property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getGraphicsFontStyle() {
        return graphicsFontStyle;
    }

    /**
     * Sets the value of the graphicsFontStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setGraphicsFontStyle(BigInteger value) {
        this.graphicsFontStyle = value;
    }

    /**
     * Gets the value of the graphicsFontWeight property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGraphicsFontWeight() {
        return graphicsFontWeight;
    }

    /**
     * Sets the value of the graphicsFontWeight property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGraphicsFontWeight(String value) {
        this.graphicsFontWeight = value;
    }

    /**
     * Gets the value of the graphicsType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGraphicsType() {
        return graphicsType;
    }

    /**
     * Sets the value of the graphicsType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGraphicsType(String value) {
        this.graphicsType = value;
    }

    /**
     * Gets the value of the height property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setHeight(BigInteger value) {
        this.height = value;
    }

    /**
     * Gets the value of the horizontalJustification property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHorizontalJustification() {
        return horizontalJustification;
    }

    /**
     * Sets the value of the horizontalJustification property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHorizontalJustification(String value) {
        this.horizontalJustification = value;
    }

    /**
     * Gets the value of the horizontalMargin property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getHorizontalMargin() {
        return horizontalMargin;
    }

    /**
     * Sets the value of the horizontalMargin property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setHorizontalMargin(BigInteger value) {
        this.horizontalMargin = value;
    }

    /**
     * Gets the value of the horizontalObjectOffset property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getHorizontalObjectOffset() {
        return horizontalObjectOffset;
    }

    /**
     * Sets the value of the horizontalObjectOffset property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setHorizontalObjectOffset(BigInteger value) {
        this.horizontalObjectOffset = value;
    }

    /**
     * Gets the value of the horizontalOrigin property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHorizontalOrigin() {
        return horizontalOrigin;
    }

    /**
     * Sets the value of the horizontalOrigin property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHorizontalOrigin(String value) {
        this.horizontalOrigin = value;
    }

    /**
     * Gets the value of the imageDepth property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getImageDepth() {
        return imageDepth;
    }

    /**
     * Sets the value of the imageDepth property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setImageDepth(String value) {
        this.imageDepth = value;
    }

    /**
     * Gets the value of the imageFormat property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getImageFormat() {
        return imageFormat;
    }

    /**
     * Sets the value of the imageFormat property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setImageFormat(String value) {
        this.imageFormat = value;
    }

    /**
     * Gets the value of the internalEndAngle property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getInternalEndAngle() {
        return internalEndAngle;
    }

    /**
     * Sets the value of the internalEndAngle property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setInternalEndAngle(BigInteger value) {
        this.internalEndAngle = value;
    }

    /**
     * Gets the value of the internalLineWidth property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getInternalLineWidth() {
        return internalLineWidth;
    }

    /**
     * Sets the value of the internalLineWidth property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setInternalLineWidth(BigInteger value) {
        this.internalLineWidth = value;
    }

    /**
     * Gets the value of the internalRotationAngle property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getInternalRotationAngle() {
        return internalRotationAngle;
    }

    /**
     * Sets the value of the internalRotationAngle property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setInternalRotationAngle(BigInteger value) {
        this.internalRotationAngle = value;
    }

    /**
     * Gets the value of the internalStartAngle property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getInternalStartAngle() {
        return internalStartAngle;
    }

    /**
     * Sets the value of the internalStartAngle property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setInternalStartAngle(BigInteger value) {
        this.internalStartAngle = value;
    }

    /**
     * Gets the value of the joinStyle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getJoinStyle() {
        return joinStyle;
    }

    /**
     * Sets the value of the joinStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setJoinStyle(String value) {
        this.joinStyle = value;
    }

    /**
     * Gets the value of the languageDirection property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLanguageDirection() {
        return languageDirection;
    }

    /**
     * Sets the value of the languageDirection property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLanguageDirection(String value) {
        this.languageDirection = value;
    }

    /**
     * Gets the value of the layoutStyle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLayoutStyle() {
        return layoutStyle;
    }

    /**
     * Sets the value of the layoutStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLayoutStyle(String value) {
        this.layoutStyle = value;
    }

    /**
     * Gets the value of the lineSpacing property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLineSpacing() {
        return lineSpacing;
    }

    /**
     * Sets the value of the lineSpacing property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLineSpacing(String value) {
        this.lineSpacing = value;
    }

    /**
     * Gets the value of the maximumObjs property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getMaximumObjs() {
        return maximumObjs;
    }

    /**
     * Sets the value of the maximumObjs property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setMaximumObjs(BigInteger value) {
        this.maximumObjs = value;
    }

    /**
     * Gets the value of the parentModuleType property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getParentModuleType() {
        return parentModuleType;
    }

    /**
     * Sets the value of the parentModuleType property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setParentModuleType(BigInteger value) {
        this.parentModuleType = value;
    }

    /**
     * Gets the value of the parentType property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getParentType() {
        return parentType;
    }

    /**
     * Sets the value of the parentType property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setParentType(BigInteger value) {
        this.parentType = value;
    }

    /**
     * Gets the value of the persistentClientInfoLength property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getPersistentClientInfoLength() {
        return persistentClientInfoLength;
    }

    /**
     * Sets the value of the persistentClientInfoLength property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setPersistentClientInfoLength(BigInteger value) {
        this.persistentClientInfoLength = value;
    }

    /**
     * Gets the value of the recordsDisplayCount property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getRecordsDisplayCount() {
        return recordsDisplayCount;
    }

    /**
     * Sets the value of the recordsDisplayCount property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setRecordsDisplayCount(BigInteger value) {
        this.recordsDisplayCount = value;
    }

    /**
     * Gets the value of the scrollbarAlign property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getScrollbarAlign() {
        return scrollbarAlign;
    }

    /**
     * Sets the value of the scrollbarAlign property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setScrollbarAlign(String value) {
        this.scrollbarAlign = value;
    }

    /**
     * Gets the value of the scrollbarWidth property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getScrollbarWidth() {
        return scrollbarWidth;
    }

    /**
     * Sets the value of the scrollbarWidth property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setScrollbarWidth(BigInteger value) {
        this.scrollbarWidth = value;
    }

    /**
     * Gets the value of the singleObjectAlign property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSingleObjectAlign() {
        return singleObjectAlign;
    }

    /**
     * Sets the value of the singleObjectAlign property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSingleObjectAlign(String value) {
        this.singleObjectAlign = value;
    }

    /**
     * Gets the value of the startPromptAlign property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStartPromptAlign() {
        return startPromptAlign;
    }

    /**
     * Sets the value of the startPromptAlign property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStartPromptAlign(String value) {
        this.startPromptAlign = value;
    }

    /**
     * Gets the value of the startPromptOffset property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getStartPromptOffset() {
        return startPromptOffset;
    }

    /**
     * Sets the value of the startPromptOffset property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setStartPromptOffset(BigInteger value) {
        this.startPromptOffset = value;
    }

    /**
     * Gets the value of the topPromptAlign property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTopPromptAlign() {
        return topPromptAlign;
    }

    /**
     * Sets the value of the topPromptAlign property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTopPromptAlign(String value) {
        this.topPromptAlign = value;
    }

    /**
     * Gets the value of the topPromptOffset property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getTopPromptOffset() {
        return topPromptOffset;
    }

    /**
     * Sets the value of the topPromptOffset property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setTopPromptOffset(BigInteger value) {
        this.topPromptOffset = value;
    }

    /**
     * Gets the value of the titleReadingOrder property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTitleReadingOrder() {
        return titleReadingOrder;
    }

    /**
     * Sets the value of the titleReadingOrder property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTitleReadingOrder(String value) {
        this.titleReadingOrder = value;
    }

    /**
     * Gets the value of the updateLayout property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUpdateLayout() {
        return updateLayout;
    }

    /**
     * Sets the value of the updateLayout property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUpdateLayout(String value) {
        this.updateLayout = value;
    }

    /**
     * Gets the value of the verticalJustification property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVerticalJustification() {
        return verticalJustification;
    }

    /**
     * Sets the value of the verticalJustification property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVerticalJustification(String value) {
        this.verticalJustification = value;
    }

    /**
     * Gets the value of the verticalMargin property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getVerticalMargin() {
        return verticalMargin;
    }

    /**
     * Sets the value of the verticalMargin property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setVerticalMargin(BigInteger value) {
        this.verticalMargin = value;
    }

    /**
     * Gets the value of the verticalObjectOffset property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getVerticalObjectOffset() {
        return verticalObjectOffset;
    }

    /**
     * Sets the value of the verticalObjectOffset property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setVerticalObjectOffset(BigInteger value) {
        this.verticalObjectOffset = value;
    }

    /**
     * Gets the value of the verticalOrigin property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVerticalOrigin() {
        return verticalOrigin;
    }

    /**
     * Sets the value of the verticalOrigin property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVerticalOrigin(String value) {
        this.verticalOrigin = value;
    }

    /**
     * Gets the value of the width property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setWidth(BigInteger value) {
        this.width = value;
    }

    /**
     * Gets the value of the xPosition property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getXPosition() {
        return xPosition;
    }

    /**
     * Sets the value of the xPosition property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setXPosition(BigInteger value) {
        this.xPosition = value;
    }

    /**
     * Gets the value of the yPosition property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getYPosition() {
        return yPosition;
    }

    /**
     * Sets the value of the yPosition property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setYPosition(BigInteger value) {
        this.yPosition = value;
    }

    /**
     * Gets the value of the backColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackColor() {
        return backColor;
    }

    /**
     * Sets the value of the backColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackColor(String value) {
        this.backColor = value;
    }

    /**
     * Gets the value of the edgeBackColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdgeBackColor() {
        return edgeBackColor;
    }

    /**
     * Sets the value of the edgeBackColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdgeBackColor(String value) {
        this.edgeBackColor = value;
    }

    /**
     * Gets the value of the edgeForegroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdgeForegroundColor() {
        return edgeForegroundColor;
    }

    /**
     * Sets the value of the edgeForegroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdgeForegroundColor(String value) {
        this.edgeForegroundColor = value;
    }

    /**
     * Gets the value of the edgePattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdgePattern() {
        return edgePattern;
    }

    /**
     * Sets the value of the edgePattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdgePattern(String value) {
        this.edgePattern = value;
    }

    /**
     * Gets the value of the fillPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillPattern() {
        return fillPattern;
    }

    /**
     * Sets the value of the fillPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillPattern(String value) {
        this.fillPattern = value;
    }

    /**
     * Gets the value of the foregroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForegroundColor() {
        return foregroundColor;
    }

    /**
     * Sets the value of the foregroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForegroundColor(String value) {
        this.foregroundColor = value;
    }

    /**
     * Gets the value of the frameTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameTitle() {
        return frameTitle;
    }

    /**
     * Sets the value of the frameTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameTitle(String value) {
        this.frameTitle = value;
    }

    /**
     * Gets the value of the frameTitleBackColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameTitleBackColor() {
        return frameTitleBackColor;
    }

    /**
     * Sets the value of the frameTitleBackColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameTitleBackColor(String value) {
        this.frameTitleBackColor = value;
    }

    /**
     * Gets the value of the frameTitleFillPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameTitleFillPattern() {
        return frameTitleFillPattern;
    }

    /**
     * Sets the value of the frameTitleFillPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameTitleFillPattern(String value) {
        this.frameTitleFillPattern = value;
    }

    /**
     * Gets the value of the frameTitleFontName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameTitleFontName() {
        return frameTitleFontName;
    }

    /**
     * Sets the value of the frameTitleFontName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameTitleFontName(String value) {
        this.frameTitleFontName = value;
    }

    /**
     * Gets the value of the frameTitleForegroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameTitleForegroundColor() {
        return frameTitleForegroundColor;
    }

    /**
     * Sets the value of the frameTitleForegroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameTitleForegroundColor(String value) {
        this.frameTitleForegroundColor = value;
    }

    /**
     * Gets the value of the frameTitleVisualAttributeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameTitleVisualAttributeName() {
        return frameTitleVisualAttributeName;
    }

    /**
     * Sets the value of the frameTitleVisualAttributeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameTitleVisualAttributeName(String value) {
        this.frameTitleVisualAttributeName = value;
    }

    /**
     * Gets the value of the graphicsFontColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGraphicsFontColor() {
        return graphicsFontColor;
    }

    /**
     * Sets the value of the graphicsFontColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGraphicsFontColor(String value) {
        this.graphicsFontColor = value;
    }

    /**
     * Gets the value of the graphicsFontName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGraphicsFontName() {
        return graphicsFontName;
    }

    /**
     * Sets the value of the graphicsFontName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGraphicsFontName(String value) {
        this.graphicsFontName = value;
    }

    /**
     * Gets the value of the graphicsText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGraphicsText() {
        return graphicsText;
    }

    /**
     * Sets the value of the graphicsText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGraphicsText(String value) {
        this.graphicsText = value;
    }

    /**
     * Gets the value of the layoutDataBlockName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLayoutDataBlockName() {
        return layoutDataBlockName;
    }

    /**
     * Sets the value of the layoutDataBlockName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLayoutDataBlockName(String value) {
        this.layoutDataBlockName = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the parentFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentFilename() {
        return parentFilename;
    }

    /**
     * Sets the value of the parentFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentFilename(String value) {
        this.parentFilename = value;
    }

    /**
     * Gets the value of the parentFilepath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentFilepath() {
        return parentFilepath;
    }

    /**
     * Sets the value of the parentFilepath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentFilepath(String value) {
        this.parentFilepath = value;
    }

    /**
     * Gets the value of the parentModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentModule() {
        return parentModule;
    }

    /**
     * Sets the value of the parentModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentModule(String value) {
        this.parentModule = value;
    }

    /**
     * Gets the value of the parentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * Sets the value of the parentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentName(String value) {
        this.parentName = value;
    }

    /**
     * Gets the value of the tabPageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTabPageName() {
        return tabPageName;
    }

    /**
     * Sets the value of the tabPageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTabPageName(String value) {
        this.tabPageName = value;
    }

    /**
     * Gets the value of the visualAttributeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisualAttributeName() {
        return visualAttributeName;
    }

    /**
     * Sets the value of the visualAttributeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisualAttributeName(String value) {
        this.visualAttributeName = value;
    }

    /**
     * Gets the value of the imageFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageFilename() {
        return imageFilename;
    }

    /**
     * Sets the value of the imageFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageFilename(String value) {
        this.imageFilename = value;
    }

    /**
     * Gets the value of the smartClass property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSmartClass() {
        return smartClass;
    }

    /**
     * Sets the value of the smartClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSmartClass(Boolean value) {
        this.smartClass = value;
    }

}
