//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 09:54:43 PM CET 
//


package com.mobissime.forms.objects;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for LOV complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LOV">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}LOVColumnMapping" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="AutoColumnWidth" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="AutoDisplay" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="AutoPosition" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="AutoRefresh" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="AutoSkip" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="AutoSelect" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DirtyInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="FilterBeforeDisplay" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="SubclassObjectGroup" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="FontSize" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FontSpacing" type="{http://xmlns.oracle.com/Forms}FontSpacingType" />
 *       &lt;attribute name="FontStyle" type="{http://xmlns.oracle.com/Forms}FontStyleType" />
 *       &lt;attribute name="FontWeight" type="{http://xmlns.oracle.com/Forms}FontWeightType" />
 *       &lt;attribute name="Height" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="LanguageDirection" type="{http://xmlns.oracle.com/Forms}LanguageDirectionType" />
 *       &lt;attribute name="ListType" type="{http://xmlns.oracle.com/Forms}ListTypeType" />
 *       &lt;attribute name="ParentModuleType" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ParentType" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="PersistentClientInfoLength" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Width" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="XPosition" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="YPosition" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="BackColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FillPattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FontName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ForegroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" use="required" type="{http://xmlns.oracle.com/Forms}nameType" />
 *       &lt;attribute name="OldLovText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentFilename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentFilepath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentModule" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RecordGroupName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="VisualAttributeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SmartClass" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LOV", propOrder = {
    "lovColumnMapping"
})
public class LOV {

    @XmlElement(name = "LOVColumnMapping")
    protected List<LOVColumnMapping> lovColumnMapping;
    @XmlAttribute(name = "AutoColumnWidth")
    protected Boolean autoColumnWidth;
    @XmlAttribute(name = "AutoDisplay")
    protected Boolean autoDisplay;
    @XmlAttribute(name = "AutoPosition")
    protected Boolean autoPosition;
    @XmlAttribute(name = "AutoRefresh")
    protected Boolean autoRefresh;
    @XmlAttribute(name = "AutoSkip")
    protected Boolean autoSkip;
    @XmlAttribute(name = "AutoSelect")
    protected Boolean autoSelect;
    @XmlAttribute(name = "DirtyInfo")
    protected Boolean dirtyInfo;
    @XmlAttribute(name = "FilterBeforeDisplay")
    protected Boolean filterBeforeDisplay;
    @XmlAttribute(name = "SubclassObjectGroup")
    protected Boolean subclassObjectGroup;
    @XmlAttribute(name = "FontSize")
    protected BigInteger fontSize;
    @XmlAttribute(name = "FontSpacing")
    protected String fontSpacing;
    @XmlAttribute(name = "FontStyle")
    protected String fontStyle;
    @XmlAttribute(name = "FontWeight")
    protected String fontWeight;
    @XmlAttribute(name = "Height")
    protected BigInteger height;
    @XmlAttribute(name = "LanguageDirection")
    protected String languageDirection;
    @XmlAttribute(name = "ListType")
    protected String listType;
    @XmlAttribute(name = "ParentModuleType")
    protected BigInteger parentModuleType;
    @XmlAttribute(name = "ParentType")
    protected BigInteger parentType;
    @XmlAttribute(name = "PersistentClientInfoLength")
    protected BigInteger persistentClientInfoLength;
    @XmlAttribute(name = "Width")
    protected BigInteger width;
    @XmlAttribute(name = "XPosition")
    protected BigInteger xPosition;
    @XmlAttribute(name = "YPosition")
    protected BigInteger yPosition;
    @XmlAttribute(name = "BackColor")
    protected String backColor;
    @XmlAttribute(name = "Comment")
    protected String comment;
    @XmlAttribute(name = "FillPattern")
    protected String fillPattern;
    @XmlAttribute(name = "FontName")
    protected String fontName;
    @XmlAttribute(name = "ForegroundColor")
    protected String foregroundColor;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "OldLovText")
    protected String oldLovText;
    @XmlAttribute(name = "ParentFilename")
    protected String parentFilename;
    @XmlAttribute(name = "ParentFilepath")
    protected String parentFilepath;
    @XmlAttribute(name = "ParentModule")
    protected String parentModule;
    @XmlAttribute(name = "ParentName")
    protected String parentName;
    @XmlAttribute(name = "RecordGroupName")
    protected String recordGroupName;
    @XmlAttribute(name = "Title")
    protected String title;
    @XmlAttribute(name = "VisualAttributeName")
    protected String visualAttributeName;
    @XmlAttribute(name = "SmartClass")
    protected Boolean smartClass;

    /**
     * Gets the value of the lovColumnMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lovColumnMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLOVColumnMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LOVColumnMapping }
     * 
     * 
     */
    public List<LOVColumnMapping> getLOVColumnMapping() {
        if (lovColumnMapping == null) {
            lovColumnMapping = new ArrayList<LOVColumnMapping>();
        }
        return this.lovColumnMapping;
    }

    /**
     * Gets the value of the autoColumnWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoColumnWidth() {
        return autoColumnWidth;
    }

    /**
     * Sets the value of the autoColumnWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoColumnWidth(Boolean value) {
        this.autoColumnWidth = value;
    }

    /**
     * Gets the value of the autoDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoDisplay() {
        return autoDisplay;
    }

    /**
     * Sets the value of the autoDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoDisplay(Boolean value) {
        this.autoDisplay = value;
    }

    /**
     * Gets the value of the autoPosition property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoPosition() {
        return autoPosition;
    }

    /**
     * Sets the value of the autoPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoPosition(Boolean value) {
        this.autoPosition = value;
    }

    /**
     * Gets the value of the autoRefresh property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoRefresh() {
        return autoRefresh;
    }

    /**
     * Sets the value of the autoRefresh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoRefresh(Boolean value) {
        this.autoRefresh = value;
    }

    /**
     * Gets the value of the autoSkip property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoSkip() {
        return autoSkip;
    }

    /**
     * Sets the value of the autoSkip property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoSkip(Boolean value) {
        this.autoSkip = value;
    }

    /**
     * Gets the value of the autoSelect property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoSelect() {
        return autoSelect;
    }

    /**
     * Sets the value of the autoSelect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoSelect(Boolean value) {
        this.autoSelect = value;
    }

    /**
     * Gets the value of the dirtyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDirtyInfo() {
        return dirtyInfo;
    }

    /**
     * Sets the value of the dirtyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDirtyInfo(Boolean value) {
        this.dirtyInfo = value;
    }

    /**
     * Gets the value of the filterBeforeDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFilterBeforeDisplay() {
        return filterBeforeDisplay;
    }

    /**
     * Sets the value of the filterBeforeDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFilterBeforeDisplay(Boolean value) {
        this.filterBeforeDisplay = value;
    }

    /**
     * Gets the value of the subclassObjectGroup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSubclassObjectGroup() {
        return subclassObjectGroup;
    }

    /**
     * Sets the value of the subclassObjectGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSubclassObjectGroup(Boolean value) {
        this.subclassObjectGroup = value;
    }

    /**
     * Gets the value of the fontSize property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getFontSize() {
        return fontSize;
    }

    /**
     * Sets the value of the fontSize property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setFontSize(BigInteger value) {
        this.fontSize = value;
    }

    /**
     * Gets the value of the fontSpacing property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFontSpacing() {
        return fontSpacing;
    }

    /**
     * Sets the value of the fontSpacing property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFontSpacing(String value) {
        this.fontSpacing = value;
    }

    /**
     * Gets the value of the fontStyle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFontStyle() {
        return fontStyle;
    }

    /**
     * Sets the value of the fontStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFontStyle(String value) {
        this.fontStyle = value;
    }

    /**
     * Gets the value of the fontWeight property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFontWeight() {
        return fontWeight;
    }

    /**
     * Sets the value of the fontWeight property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFontWeight(String value) {
        this.fontWeight = value;
    }

    /**
     * Gets the value of the height property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setHeight(BigInteger value) {
        this.height = value;
    }

    /**
     * Gets the value of the languageDirection property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLanguageDirection() {
        return languageDirection;
    }

    /**
     * Sets the value of the languageDirection property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLanguageDirection(String value) {
        this.languageDirection = value;
    }

    /**
     * Gets the value of the listType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getListType() {
        return listType;
    }

    /**
     * Sets the value of the listType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setListType(String value) {
        this.listType = value;
    }

    /**
     * Gets the value of the parentModuleType property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getParentModuleType() {
        return parentModuleType;
    }

    /**
     * Sets the value of the parentModuleType property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setParentModuleType(BigInteger value) {
        this.parentModuleType = value;
    }

    /**
     * Gets the value of the parentType property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getParentType() {
        return parentType;
    }

    /**
     * Sets the value of the parentType property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setParentType(BigInteger value) {
        this.parentType = value;
    }

    /**
     * Gets the value of the persistentClientInfoLength property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getPersistentClientInfoLength() {
        return persistentClientInfoLength;
    }

    /**
     * Sets the value of the persistentClientInfoLength property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setPersistentClientInfoLength(BigInteger value) {
        this.persistentClientInfoLength = value;
    }

    /**
     * Gets the value of the width property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setWidth(BigInteger value) {
        this.width = value;
    }

    /**
     * Gets the value of the xPosition property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getXPosition() {
        return xPosition;
    }

    /**
     * Sets the value of the xPosition property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setXPosition(BigInteger value) {
        this.xPosition = value;
    }

    /**
     * Gets the value of the yPosition property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getYPosition() {
        return yPosition;
    }

    /**
     * Sets the value of the yPosition property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setYPosition(BigInteger value) {
        this.yPosition = value;
    }

    /**
     * Gets the value of the backColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackColor() {
        return backColor;
    }

    /**
     * Sets the value of the backColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackColor(String value) {
        this.backColor = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the fillPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillPattern() {
        return fillPattern;
    }

    /**
     * Sets the value of the fillPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillPattern(String value) {
        this.fillPattern = value;
    }

    /**
     * Gets the value of the fontName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontName() {
        return fontName;
    }

    /**
     * Sets the value of the fontName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontName(String value) {
        this.fontName = value;
    }

    /**
     * Gets the value of the foregroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForegroundColor() {
        return foregroundColor;
    }

    /**
     * Sets the value of the foregroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForegroundColor(String value) {
        this.foregroundColor = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the oldLovText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldLovText() {
        return oldLovText;
    }

    /**
     * Sets the value of the oldLovText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldLovText(String value) {
        this.oldLovText = value;
    }

    /**
     * Gets the value of the parentFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentFilename() {
        return parentFilename;
    }

    /**
     * Sets the value of the parentFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentFilename(String value) {
        this.parentFilename = value;
    }

    /**
     * Gets the value of the parentFilepath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentFilepath() {
        return parentFilepath;
    }

    /**
     * Sets the value of the parentFilepath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentFilepath(String value) {
        this.parentFilepath = value;
    }

    /**
     * Gets the value of the parentModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentModule() {
        return parentModule;
    }

    /**
     * Sets the value of the parentModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentModule(String value) {
        this.parentModule = value;
    }

    /**
     * Gets the value of the parentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * Sets the value of the parentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentName(String value) {
        this.parentName = value;
    }

    /**
     * Gets the value of the recordGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordGroupName() {
        return recordGroupName;
    }

    /**
     * Sets the value of the recordGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordGroupName(String value) {
        this.recordGroupName = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the visualAttributeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisualAttributeName() {
        return visualAttributeName;
    }

    /**
     * Sets the value of the visualAttributeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisualAttributeName(String value) {
        this.visualAttributeName = value;
    }

    /**
     * Gets the value of the smartClass property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSmartClass() {
        return smartClass;
    }

    /**
     * Sets the value of the smartClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSmartClass(Boolean value) {
        this.smartClass = value;
    }

}
