//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 09:54:43 PM CET 
//


package com.mobissime.forms.objects;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for Module complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Module">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}FormModule"/>
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}ObjectLibrary"/>
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}MenuModule"/>
 *       &lt;/choice>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="Module")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Module", propOrder = {
    "formModule",
    "objectLibrary",
    "menuModule"
})
public class Module {

    @XmlElement(name = "FormModule")
    protected FormModule formModule;
    @XmlElement(name = "ObjectLibrary")
    protected ObjectLibrary objectLibrary;
    @XmlElement(name = "MenuModule")
    protected MenuModule menuModule;
    @XmlAttribute(name = "version")
    protected Long version;

    /**
     * Gets the value of the formModule property.
     * 
     * @return
     *     possible object is
     *     {@link FormModule }
     *     
     */
    public FormModule getFormModule() {
        return formModule;
    }

    /**
     * Sets the value of the formModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormModule }
     *     
     */
    public void setFormModule(FormModule value) {
        this.formModule = value;
    }

    /**
     * Gets the value of the objectLibrary property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectLibrary }
     *     
     */
    public ObjectLibrary getObjectLibrary() {
        return objectLibrary;
    }

    /**
     * Sets the value of the objectLibrary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectLibrary }
     *     
     */
    public void setObjectLibrary(ObjectLibrary value) {
        this.objectLibrary = value;
    }

    /**
     * Gets the value of the menuModule property.
     * 
     * @return
     *     possible object is
     *     {@link MenuModule }
     *     
     */
    public MenuModule getMenuModule() {
        return menuModule;
    }

    /**
     * Sets the value of the menuModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link MenuModule }
     *     
     */
    public void setMenuModule(MenuModule value) {
        this.menuModule = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVersion(Long value) {
        this.version = value;
    }

}
