//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 09:54:43 PM CET 
//


package com.mobissime.forms.objects;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for RecordGroupColumn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecordGroupColumn">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}RecordGroupColumnRow" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="DirtyInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ColumnDataType" type="{http://xmlns.oracle.com/Forms}ColumnDataTypeType" />
 *       &lt;attribute name="ColumnValuesCount" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="DataLengthSemantics" type="{http://xmlns.oracle.com/Forms}DataLengthSemanticsType" />
 *       &lt;attribute name="MaximumLength" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="PersistentClientInfoLength" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Name" use="required" type="{http://xmlns.oracle.com/Forms}nameType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecordGroupColumn", propOrder = {
    "recordGroupColumnRow"
})
public class RecordGroupColumn {

    @XmlElement(name = "RecordGroupColumnRow")
    protected List<IndexedListWithoutName> recordGroupColumnRow;
    @XmlAttribute(name = "DirtyInfo")
    protected Boolean dirtyInfo;
    @XmlAttribute(name = "ColumnDataType")
    protected String columnDataType;
    @XmlAttribute(name = "ColumnValuesCount")
    protected BigInteger columnValuesCount;
    @XmlAttribute(name = "DataLengthSemantics")
    protected String dataLengthSemantics;
    @XmlAttribute(name = "MaximumLength")
    protected BigInteger maximumLength;
    @XmlAttribute(name = "PersistentClientInfoLength")
    protected BigInteger persistentClientInfoLength;
    @XmlAttribute(name = "Name", required = true)
    protected String name;

    /**
     * Gets the value of the recordGroupColumnRow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recordGroupColumnRow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecordGroupColumnRow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IndexedListWithoutName }
     * 
     * 
     */
    public List<IndexedListWithoutName> getRecordGroupColumnRow() {
        if (recordGroupColumnRow == null) {
            recordGroupColumnRow = new ArrayList<IndexedListWithoutName>();
        }
        return this.recordGroupColumnRow;
    }

    /**
     * Gets the value of the dirtyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDirtyInfo() {
        return dirtyInfo;
    }

    /**
     * Sets the value of the dirtyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDirtyInfo(Boolean value) {
        this.dirtyInfo = value;
    }

    /**
     * Gets the value of the columnDataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnDataType() {
        return columnDataType;
    }

    /**
     * Sets the value of the columnDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnDataType(String value) {
        this.columnDataType = value;
    }

    /**
     * Gets the value of the columnValuesCount property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getColumnValuesCount() {
        return columnValuesCount;
    }

    /**
     * Sets the value of the columnValuesCount property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setColumnValuesCount(BigInteger value) {
        this.columnValuesCount = value;
    }

    /**
     * Gets the value of the dataLengthSemantics property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDataLengthSemantics() {
        return dataLengthSemantics;
    }

    /**
     * Sets the value of the dataLengthSemantics property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDataLengthSemantics(String value) {
        this.dataLengthSemantics = value;
    }

    /**
     * Gets the value of the maximumLength property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getMaximumLength() {
        return maximumLength;
    }

    /**
     * Sets the value of the maximumLength property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setMaximumLength(BigInteger value) {
        this.maximumLength = value;
    }

    /**
     * Gets the value of the persistentClientInfoLength property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getPersistentClientInfoLength() {
        return persistentClientInfoLength;
    }

    /**
     * Sets the value of the persistentClientInfoLength property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setPersistentClientInfoLength(BigInteger value) {
        this.persistentClientInfoLength = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
