//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 09:54:43 PM CET 
//


package com.mobissime.forms.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for Trigger complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Trigger">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DirtyInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DisplayInKeyboardHelp" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="FireInQuery" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Hide" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="SubclassObjectGroup" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="SubclassSubObject" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ExecuteHierarchy" type="{http://xmlns.oracle.com/Forms}ExecuteHierarchyType" />
 *       &lt;attribute name="ParentModuleType" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ParentSourceLevel1ObjectType" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ParentSourceLevel2ObjectType" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ParentType" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="PersistentClientInfoLength" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="TriggerInternalType" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="TriggerStyle" type="{http://xmlns.oracle.com/Forms}TriggerStyleType" />
 *       &lt;attribute name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="KeyboardHelpText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" use="required" type="{http://xmlns.oracle.com/Forms}nameType" />
 *       &lt;attribute name="ParentFilename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentFilepath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentModule" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentSourceLevel1ObjectName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentSourceLevel2ObjectName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TriggerText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SmartClass" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Trigger")
public class Trigger {

    @XmlAttribute(name = "DirtyInfo")
    protected Boolean dirtyInfo;
    @XmlAttribute(name = "DisplayInKeyboardHelp")
    protected Boolean displayInKeyboardHelp;
    @XmlAttribute(name = "FireInQuery")
    protected Boolean fireInQuery;
    @XmlAttribute(name = "Hide")
    protected Boolean hide;
    @XmlAttribute(name = "SubclassObjectGroup")
    protected Boolean subclassObjectGroup;
    @XmlAttribute(name = "SubclassSubObject")
    protected Boolean subclassSubObject;
    @XmlAttribute(name = "ExecuteHierarchy")
    protected String executeHierarchy;
    @XmlAttribute(name = "ParentModuleType")
    protected BigInteger parentModuleType;
    @XmlAttribute(name = "ParentSourceLevel1ObjectType")
    protected BigInteger parentSourceLevel1ObjectType;
    @XmlAttribute(name = "ParentSourceLevel2ObjectType")
    protected BigInteger parentSourceLevel2ObjectType;
    @XmlAttribute(name = "ParentType")
    protected BigInteger parentType;
    @XmlAttribute(name = "PersistentClientInfoLength")
    protected BigInteger persistentClientInfoLength;
    @XmlAttribute(name = "TriggerInternalType")
    protected BigInteger triggerInternalType;
    @XmlAttribute(name = "TriggerStyle")
    protected String triggerStyle;
    @XmlAttribute(name = "Comment")
    protected String comment;
    @XmlAttribute(name = "KeyboardHelpText")
    protected String keyboardHelpText;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "ParentFilename")
    protected String parentFilename;
    @XmlAttribute(name = "ParentFilepath")
    protected String parentFilepath;
    @XmlAttribute(name = "ParentModule")
    protected String parentModule;
    @XmlAttribute(name = "ParentName")
    protected String parentName;
    @XmlAttribute(name = "ParentSourceLevel1ObjectName")
    protected String parentSourceLevel1ObjectName;
    @XmlAttribute(name = "ParentSourceLevel2ObjectName")
    protected String parentSourceLevel2ObjectName;
    @XmlAttribute(name = "TriggerText")
    protected String triggerText;
    @XmlAttribute(name = "SmartClass")
    protected Boolean smartClass;

    /**
     * Gets the value of the dirtyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDirtyInfo() {
        return dirtyInfo;
    }

    /**
     * Sets the value of the dirtyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDirtyInfo(Boolean value) {
        this.dirtyInfo = value;
    }

    /**
     * Gets the value of the displayInKeyboardHelp property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisplayInKeyboardHelp() {
        return displayInKeyboardHelp;
    }

    /**
     * Sets the value of the displayInKeyboardHelp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisplayInKeyboardHelp(Boolean value) {
        this.displayInKeyboardHelp = value;
    }

    /**
     * Gets the value of the fireInQuery property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFireInQuery() {
        return fireInQuery;
    }

    /**
     * Sets the value of the fireInQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFireInQuery(Boolean value) {
        this.fireInQuery = value;
    }

    /**
     * Gets the value of the hide property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHide() {
        return hide;
    }

    /**
     * Sets the value of the hide property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHide(Boolean value) {
        this.hide = value;
    }

    /**
     * Gets the value of the subclassObjectGroup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSubclassObjectGroup() {
        return subclassObjectGroup;
    }

    /**
     * Sets the value of the subclassObjectGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSubclassObjectGroup(Boolean value) {
        this.subclassObjectGroup = value;
    }

    /**
     * Gets the value of the subclassSubObject property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSubclassSubObject() {
        return subclassSubObject;
    }

    /**
     * Sets the value of the subclassSubObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSubclassSubObject(Boolean value) {
        this.subclassSubObject = value;
    }

    /**
     * Gets the value of the executeHierarchy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecuteHierarchy() {
        return executeHierarchy;
    }

    /**
     * Sets the value of the executeHierarchy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecuteHierarchy(String value) {
        this.executeHierarchy = value;
    }

    /**
     * Gets the value of the parentModuleType property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getParentModuleType() {
        return parentModuleType;
    }

    /**
     * Sets the value of the parentModuleType property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setParentModuleType(BigInteger value) {
        this.parentModuleType = value;
    }

    /**
     * Gets the value of the parentSourceLevel1ObjectType property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getParentSourceLevel1ObjectType() {
        return parentSourceLevel1ObjectType;
    }

    /**
     * Sets the value of the parentSourceLevel1ObjectType property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setParentSourceLevel1ObjectType(BigInteger value) {
        this.parentSourceLevel1ObjectType = value;
    }

    /**
     * Gets the value of the parentSourceLevel2ObjectType property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getParentSourceLevel2ObjectType() {
        return parentSourceLevel2ObjectType;
    }

    /**
     * Sets the value of the parentSourceLevel2ObjectType property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setParentSourceLevel2ObjectType(BigInteger value) {
        this.parentSourceLevel2ObjectType = value;
    }

    /**
     * Gets the value of the parentType property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getParentType() {
        return parentType;
    }

    /**
     * Sets the value of the parentType property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setParentType(BigInteger value) {
        this.parentType = value;
    }

    /**
     * Gets the value of the persistentClientInfoLength property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getPersistentClientInfoLength() {
        return persistentClientInfoLength;
    }

    /**
     * Sets the value of the persistentClientInfoLength property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setPersistentClientInfoLength(BigInteger value) {
        this.persistentClientInfoLength = value;
    }

    /**
     * Gets the value of the triggerInternalType property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getTriggerInternalType() {
        return triggerInternalType;
    }

    /**
     * Sets the value of the triggerInternalType property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setTriggerInternalType(BigInteger value) {
        this.triggerInternalType = value;
    }

    /**
     * Gets the value of the triggerStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTriggerStyle() {
        return triggerStyle;
    }

    /**
     * Sets the value of the triggerStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTriggerStyle(String value) {
        this.triggerStyle = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the keyboardHelpText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyboardHelpText() {
        return keyboardHelpText;
    }

    /**
     * Sets the value of the keyboardHelpText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyboardHelpText(String value) {
        this.keyboardHelpText = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the parentFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentFilename() {
        return parentFilename;
    }

    /**
     * Sets the value of the parentFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentFilename(String value) {
        this.parentFilename = value;
    }

    /**
     * Gets the value of the parentFilepath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentFilepath() {
        return parentFilepath;
    }

    /**
     * Sets the value of the parentFilepath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentFilepath(String value) {
        this.parentFilepath = value;
    }

    /**
     * Gets the value of the parentModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentModule() {
        return parentModule;
    }

    /**
     * Sets the value of the parentModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentModule(String value) {
        this.parentModule = value;
    }

    /**
     * Gets the value of the parentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * Sets the value of the parentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentName(String value) {
        this.parentName = value;
    }

    /**
     * Gets the value of the parentSourceLevel1ObjectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentSourceLevel1ObjectName() {
        return parentSourceLevel1ObjectName;
    }

    /**
     * Sets the value of the parentSourceLevel1ObjectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentSourceLevel1ObjectName(String value) {
        this.parentSourceLevel1ObjectName = value;
    }

    /**
     * Gets the value of the parentSourceLevel2ObjectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentSourceLevel2ObjectName() {
        return parentSourceLevel2ObjectName;
    }

    /**
     * Sets the value of the parentSourceLevel2ObjectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentSourceLevel2ObjectName(String value) {
        this.parentSourceLevel2ObjectName = value;
    }

    /**
     * Gets the value of the triggerText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTriggerText() {
        return triggerText;
    }

    /**
     * Sets the value of the triggerText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTriggerText(String value) {
        this.triggerText = value;
    }

    /**
     * Gets the value of the smartClass property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSmartClass() {
        return smartClass;
    }

    /**
     * Sets the value of the smartClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSmartClass(Boolean value) {
        this.smartClass = value;
    }

}
