//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 09:54:43 PM CET 
//


package com.mobissime.forms.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for VisualAttribute complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VisualAttribute">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DirtyInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="SubclassObjectGroup" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="FontSize" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FontSpacing" type="{http://xmlns.oracle.com/Forms}FontSpacingType" />
 *       &lt;attribute name="FontStyle" type="{http://xmlns.oracle.com/Forms}FontStyleType" />
 *       &lt;attribute name="FontWeight" type="{http://xmlns.oracle.com/Forms}FontWeightType" />
 *       &lt;attribute name="FrameTitleFontSize" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FrameTitleFontSpacing" type="{http://xmlns.oracle.com/Forms}FrameTitleFontSpacingType" />
 *       &lt;attribute name="FrameTitleFontStyle" type="{http://xmlns.oracle.com/Forms}FrameTitleFontStyleType" />
 *       &lt;attribute name="FrameTitleFontWeight" type="{http://xmlns.oracle.com/Forms}FrameTitleFontWeightType" />
 *       &lt;attribute name="ParentModuleType" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ParentType" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="PersistentClientInfoLength" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="PromptFontSize" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="PromptFontSpacing" type="{http://xmlns.oracle.com/Forms}PromptFontSpacingType" />
 *       &lt;attribute name="PromptFontStyle" type="{http://xmlns.oracle.com/Forms}PromptFontStyleType" />
 *       &lt;attribute name="PromptFontWeight" type="{http://xmlns.oracle.com/Forms}PromptFontWeightType" />
 *       &lt;attribute name="VisualAttributeType" type="{http://xmlns.oracle.com/Forms}VisualAttributeTypeType" />
 *       &lt;attribute name="BackColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FillPattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FontName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ForegroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FrameTitleBackColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FrameTitleFillPattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FrameTitleFontName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FrameTitleForegroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" use="required" type="{http://xmlns.oracle.com/Forms}nameType" />
 *       &lt;attribute name="ParentFilename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentFilepath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentModule" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ParentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PromptBackColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PromptFillPattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PromptFontName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PromptForegroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SmartClass" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisualAttribute")
public class VisualAttribute {

    @XmlAttribute(name = "DirtyInfo")
    protected Boolean dirtyInfo;
    @XmlAttribute(name = "SubclassObjectGroup")
    protected Boolean subclassObjectGroup;
    @XmlAttribute(name = "FontSize")
    protected BigInteger fontSize;
    @XmlAttribute(name = "FontSpacing")
    protected String fontSpacing;
    @XmlAttribute(name = "FontStyle")
    protected String fontStyle;
    @XmlAttribute(name = "FontWeight")
    protected String fontWeight;
    @XmlAttribute(name = "FrameTitleFontSize")
    protected BigInteger frameTitleFontSize;
    @XmlAttribute(name = "FrameTitleFontSpacing")
    protected String frameTitleFontSpacing;
    @XmlAttribute(name = "FrameTitleFontStyle")
    protected String frameTitleFontStyle;
    @XmlAttribute(name = "FrameTitleFontWeight")
    protected String frameTitleFontWeight;
    @XmlAttribute(name = "ParentModuleType")
    protected BigInteger parentModuleType;
    @XmlAttribute(name = "ParentType")
    protected BigInteger parentType;
    @XmlAttribute(name = "PersistentClientInfoLength")
    protected BigInteger persistentClientInfoLength;
    @XmlAttribute(name = "PromptFontSize")
    protected BigInteger promptFontSize;
    @XmlAttribute(name = "PromptFontSpacing")
    protected String promptFontSpacing;
    @XmlAttribute(name = "PromptFontStyle")
    protected String promptFontStyle;
    @XmlAttribute(name = "PromptFontWeight")
    protected String promptFontWeight;
    @XmlAttribute(name = "VisualAttributeType")
    protected String visualAttributeType;
    @XmlAttribute(name = "BackColor")
    protected String backColor;
    @XmlAttribute(name = "Comment")
    protected String comment;
    @XmlAttribute(name = "FillPattern")
    protected String fillPattern;
    @XmlAttribute(name = "FontName")
    protected String fontName;
    @XmlAttribute(name = "ForegroundColor")
    protected String foregroundColor;
    @XmlAttribute(name = "FrameTitleBackColor")
    protected String frameTitleBackColor;
    @XmlAttribute(name = "FrameTitleFillPattern")
    protected String frameTitleFillPattern;
    @XmlAttribute(name = "FrameTitleFontName")
    protected String frameTitleFontName;
    @XmlAttribute(name = "FrameTitleForegroundColor")
    protected String frameTitleForegroundColor;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "ParentFilename")
    protected String parentFilename;
    @XmlAttribute(name = "ParentFilepath")
    protected String parentFilepath;
    @XmlAttribute(name = "ParentModule")
    protected String parentModule;
    @XmlAttribute(name = "ParentName")
    protected String parentName;
    @XmlAttribute(name = "PromptBackColor")
    protected String promptBackColor;
    @XmlAttribute(name = "PromptFillPattern")
    protected String promptFillPattern;
    @XmlAttribute(name = "PromptFontName")
    protected String promptFontName;
    @XmlAttribute(name = "PromptForegroundColor")
    protected String promptForegroundColor;
    @XmlAttribute(name = "SmartClass")
    protected Boolean smartClass;

    /**
     * Gets the value of the dirtyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDirtyInfo() {
        return dirtyInfo;
    }

    /**
     * Sets the value of the dirtyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDirtyInfo(Boolean value) {
        this.dirtyInfo = value;
    }

    /**
     * Gets the value of the subclassObjectGroup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSubclassObjectGroup() {
        return subclassObjectGroup;
    }

    /**
     * Sets the value of the subclassObjectGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSubclassObjectGroup(Boolean value) {
        this.subclassObjectGroup = value;
    }

    /**
     * Gets the value of the fontSize property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getFontSize() {
        return fontSize;
    }

    /**
     * Sets the value of the fontSize property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setFontSize(BigInteger value) {
        this.fontSize = value;
    }

    /**
     * Gets the value of the fontSpacing property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFontSpacing() {
        return fontSpacing;
    }

    /**
     * Sets the value of the fontSpacing property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFontSpacing(String value) {
        this.fontSpacing = value;
    }

    /**
     * Gets the value of the fontStyle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFontStyle() {
        return fontStyle;
    }

    /**
     * Sets the value of the fontStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFontStyle(String value) {
        this.fontStyle = value;
    }

    /**
     * Gets the value of the fontWeight property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFontWeight() {
        return fontWeight;
    }

    /**
     * Sets the value of the fontWeight property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFontWeight(String value) {
        this.fontWeight = value;
    }

    /**
     * Gets the value of the frameTitleFontSize property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getFrameTitleFontSize() {
        return frameTitleFontSize;
    }

    /**
     * Sets the value of the frameTitleFontSize property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setFrameTitleFontSize(BigInteger value) {
        this.frameTitleFontSize = value;
    }

    /**
     * Gets the value of the frameTitleFontSpacing property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFrameTitleFontSpacing() {
        return frameTitleFontSpacing;
    }

    /**
     * Sets the value of the frameTitleFontSpacing property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFrameTitleFontSpacing(String value) {
        this.frameTitleFontSpacing = value;
    }

    /**
     * Gets the value of the frameTitleFontStyle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFrameTitleFontStyle() {
        return frameTitleFontStyle;
    }

    /**
     * Sets the value of the frameTitleFontStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFrameTitleFontStyle(String value) {
        this.frameTitleFontStyle = value;
    }

    /**
     * Gets the value of the frameTitleFontWeight property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFrameTitleFontWeight() {
        return frameTitleFontWeight;
    }

    /**
     * Sets the value of the frameTitleFontWeight property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFrameTitleFontWeight(String value) {
        this.frameTitleFontWeight = value;
    }

    /**
     * Gets the value of the parentModuleType property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getParentModuleType() {
        return parentModuleType;
    }

    /**
     * Sets the value of the parentModuleType property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setParentModuleType(BigInteger value) {
        this.parentModuleType = value;
    }

    /**
     * Gets the value of the parentType property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getParentType() {
        return parentType;
    }

    /**
     * Sets the value of the parentType property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setParentType(BigInteger value) {
        this.parentType = value;
    }

    /**
     * Gets the value of the persistentClientInfoLength property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getPersistentClientInfoLength() {
        return persistentClientInfoLength;
    }

    /**
     * Sets the value of the persistentClientInfoLength property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setPersistentClientInfoLength(BigInteger value) {
        this.persistentClientInfoLength = value;
    }

    /**
     * Gets the value of the promptFontSize property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getPromptFontSize() {
        return promptFontSize;
    }

    /**
     * Sets the value of the promptFontSize property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setPromptFontSize(BigInteger value) {
        this.promptFontSize = value;
    }

    /**
     * Gets the value of the promptFontSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromptFontSpacing() {
        return promptFontSpacing;
    }

    /**
     * Sets the value of the promptFontSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromptFontSpacing(String value) {
        this.promptFontSpacing = value;
    }

    /**
     * Gets the value of the promptFontStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromptFontStyle() {
        return promptFontStyle;
    }

    /**
     * Sets the value of the promptFontStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromptFontStyle(String value) {
        this.promptFontStyle = value;
    }

    /**
     * Gets the value of the promptFontWeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromptFontWeight() {
        return promptFontWeight;
    }

    /**
     * Sets the value of the promptFontWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromptFontWeight(String value) {
        this.promptFontWeight = value;
    }

    /**
     * Gets the value of the visualAttributeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisualAttributeType() {
        return visualAttributeType;
    }

    /**
     * Sets the value of the visualAttributeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisualAttributeType(String value) {
        this.visualAttributeType = value;
    }

    /**
     * Gets the value of the backColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackColor() {
        return backColor;
    }

    /**
     * Sets the value of the backColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackColor(String value) {
        this.backColor = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the fillPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillPattern() {
        return fillPattern;
    }

    /**
     * Sets the value of the fillPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillPattern(String value) {
        this.fillPattern = value;
    }

    /**
     * Gets the value of the fontName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontName() {
        return fontName;
    }

    /**
     * Sets the value of the fontName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontName(String value) {
        this.fontName = value;
    }

    /**
     * Gets the value of the foregroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForegroundColor() {
        return foregroundColor;
    }

    /**
     * Sets the value of the foregroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForegroundColor(String value) {
        this.foregroundColor = value;
    }

    /**
     * Gets the value of the frameTitleBackColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameTitleBackColor() {
        return frameTitleBackColor;
    }

    /**
     * Sets the value of the frameTitleBackColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameTitleBackColor(String value) {
        this.frameTitleBackColor = value;
    }

    /**
     * Gets the value of the frameTitleFillPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameTitleFillPattern() {
        return frameTitleFillPattern;
    }

    /**
     * Sets the value of the frameTitleFillPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameTitleFillPattern(String value) {
        this.frameTitleFillPattern = value;
    }

    /**
     * Gets the value of the frameTitleFontName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameTitleFontName() {
        return frameTitleFontName;
    }

    /**
     * Sets the value of the frameTitleFontName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameTitleFontName(String value) {
        this.frameTitleFontName = value;
    }

    /**
     * Gets the value of the frameTitleForegroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameTitleForegroundColor() {
        return frameTitleForegroundColor;
    }

    /**
     * Sets the value of the frameTitleForegroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameTitleForegroundColor(String value) {
        this.frameTitleForegroundColor = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the parentFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentFilename() {
        return parentFilename;
    }

    /**
     * Sets the value of the parentFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentFilename(String value) {
        this.parentFilename = value;
    }

    /**
     * Gets the value of the parentFilepath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentFilepath() {
        return parentFilepath;
    }

    /**
     * Sets the value of the parentFilepath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentFilepath(String value) {
        this.parentFilepath = value;
    }

    /**
     * Gets the value of the parentModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentModule() {
        return parentModule;
    }

    /**
     * Sets the value of the parentModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentModule(String value) {
        this.parentModule = value;
    }

    /**
     * Gets the value of the parentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * Sets the value of the parentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentName(String value) {
        this.parentName = value;
    }

    /**
     * Gets the value of the promptBackColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromptBackColor() {
        return promptBackColor;
    }

    /**
     * Sets the value of the promptBackColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromptBackColor(String value) {
        this.promptBackColor = value;
    }

    /**
     * Gets the value of the promptFillPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromptFillPattern() {
        return promptFillPattern;
    }

    /**
     * Sets the value of the promptFillPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromptFillPattern(String value) {
        this.promptFillPattern = value;
    }

    /**
     * Gets the value of the promptFontName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromptFontName() {
        return promptFontName;
    }

    /**
     * Sets the value of the promptFontName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromptFontName(String value) {
        this.promptFontName = value;
    }

    /**
     * Gets the value of the promptForegroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromptForegroundColor() {
        return promptForegroundColor;
    }

    /**
     * Sets the value of the promptForegroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromptForegroundColor(String value) {
        this.promptForegroundColor = value;
    }

    /**
     * Gets the value of the smartClass property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSmartClass() {
        return smartClass;
    }

    /**
     * Sets the value of the smartClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSmartClass(Boolean value) {
        this.smartClass = value;
    }

}
