//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 09:54:43 PM CET 
//


package com.mobissime.forms.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for VisualState complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VisualState">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="BoundingBoxScalable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="CenterTracking" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Closed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Dither" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="FixedBoundingBox" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="FontScaleable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="GridFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="GridsnapFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="PageCountSeq" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="PagebreakFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ResizableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="RulerFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="RulerGuideFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ShowCanvas" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ShowView" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="StatusLineFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ToolpaletteFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="VisualStateValid" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="WrapText" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ArrowStyle" type="{http://xmlns.oracle.com/Forms}ArrowStyleType" />
 *       &lt;attribute name="CapStyle" type="{http://xmlns.oracle.com/Forms}CapStyleType" />
 *       &lt;attribute name="CharacterCellHden" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="CharacterCellHnum" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="CharacterCellVden" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="CharacterCellVnum" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="CornerRadiusX" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="CornerRadiusY" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="DashStyle" type="{http://xmlns.oracle.com/Forms}DashStyleType" />
 *       &lt;attribute name="DisplayQuality" type="{http://xmlns.oracle.com/Forms}DisplayQualityType" />
 *       &lt;attribute name="DrawingHden" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="DrawingHnum" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="DrawingWden" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="DrawingWnum" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="EditorHeight" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="EditorWidth" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FontSize" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FontSpacing" type="{http://xmlns.oracle.com/Forms}FontSpacingType" />
 *       &lt;attribute name="FontStyle" type="{http://xmlns.oracle.com/Forms}FontStyleType" />
 *       &lt;attribute name="FontWeight" type="{http://xmlns.oracle.com/Forms}FontWeightType" />
 *       &lt;attribute name="FrameTitleAlign" type="{http://xmlns.oracle.com/Forms}FrameTitleAlignType" />
 *       &lt;attribute name="FrameTitleOffset" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FrameTitleSpacing" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="GridIntervalCnt" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="GridSnapCnt" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="GridUnitCnt" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="InternalLineWidth" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="InternalRotationAngle" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="RulerMajor" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="RulerMinor" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="RulerUnit" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="WindowHeight" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="WindowWidth" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="WindowXPosition" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="WindowYPosition" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ZoomLevel" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="BackColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EdgeBackColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EdgeForegroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EdgePattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FillPattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FontName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ForegroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisualState")
public class VisualState {

    @XmlAttribute(name = "BoundingBoxScalable")
    protected Boolean boundingBoxScalable;
    @XmlAttribute(name = "CenterTracking")
    protected Boolean centerTracking;
    @XmlAttribute(name = "Closed")
    protected Boolean closed;
    @XmlAttribute(name = "Dither")
    protected Boolean dither;
    @XmlAttribute(name = "FixedBoundingBox")
    protected Boolean fixedBoundingBox;
    @XmlAttribute(name = "FontScaleable")
    protected Boolean fontScaleable;
    @XmlAttribute(name = "GridFlag")
    protected Boolean gridFlag;
    @XmlAttribute(name = "GridsnapFlag")
    protected Boolean gridsnapFlag;
    @XmlAttribute(name = "PageCountSeq")
    protected Boolean pageCountSeq;
    @XmlAttribute(name = "PagebreakFlag")
    protected Boolean pagebreakFlag;
    @XmlAttribute(name = "ResizableFlag")
    protected Boolean resizableFlag;
    @XmlAttribute(name = "RulerFlag")
    protected Boolean rulerFlag;
    @XmlAttribute(name = "RulerGuideFlag")
    protected Boolean rulerGuideFlag;
    @XmlAttribute(name = "ShowCanvas")
    protected Boolean showCanvas;
    @XmlAttribute(name = "ShowView")
    protected Boolean showView;
    @XmlAttribute(name = "StatusLineFlag")
    protected Boolean statusLineFlag;
    @XmlAttribute(name = "ToolpaletteFlag")
    protected Boolean toolpaletteFlag;
    @XmlAttribute(name = "VisualStateValid")
    protected Boolean visualStateValid;
    @XmlAttribute(name = "WrapText")
    protected Boolean wrapText;
    @XmlAttribute(name = "ArrowStyle")
    protected String arrowStyle;
    @XmlAttribute(name = "CapStyle")
    protected String capStyle;
    @XmlAttribute(name = "CharacterCellHden")
    protected BigInteger characterCellHden;
    @XmlAttribute(name = "CharacterCellHnum")
    protected BigInteger characterCellHnum;
    @XmlAttribute(name = "CharacterCellVden")
    protected BigInteger characterCellVden;
    @XmlAttribute(name = "CharacterCellVnum")
    protected BigInteger characterCellVnum;
    @XmlAttribute(name = "CornerRadiusX")
    protected BigInteger cornerRadiusX;
    @XmlAttribute(name = "CornerRadiusY")
    protected BigInteger cornerRadiusY;
    @XmlAttribute(name = "DashStyle")
    protected String dashStyle;
    @XmlAttribute(name = "DisplayQuality")
    protected String displayQuality;
    @XmlAttribute(name = "DrawingHden")
    protected BigInteger drawingHden;
    @XmlAttribute(name = "DrawingHnum")
    protected BigInteger drawingHnum;
    @XmlAttribute(name = "DrawingWden")
    protected BigInteger drawingWden;
    @XmlAttribute(name = "DrawingWnum")
    protected BigInteger drawingWnum;
    @XmlAttribute(name = "EditorHeight")
    protected BigInteger editorHeight;
    @XmlAttribute(name = "EditorWidth")
    protected BigInteger editorWidth;
    @XmlAttribute(name = "FontSize")
    protected BigInteger fontSize;
    @XmlAttribute(name = "FontSpacing")
    protected String fontSpacing;
    @XmlAttribute(name = "FontStyle")
    protected String fontStyle;
    @XmlAttribute(name = "FontWeight")
    protected String fontWeight;
    @XmlAttribute(name = "FrameTitleAlign")
    protected String frameTitleAlign;
    @XmlAttribute(name = "FrameTitleOffset")
    protected BigInteger frameTitleOffset;
    @XmlAttribute(name = "FrameTitleSpacing")
    protected BigInteger frameTitleSpacing;
    @XmlAttribute(name = "GridIntervalCnt")
    protected BigInteger gridIntervalCnt;
    @XmlAttribute(name = "GridSnapCnt")
    protected BigInteger gridSnapCnt;
    @XmlAttribute(name = "GridUnitCnt")
    protected BigInteger gridUnitCnt;
    @XmlAttribute(name = "InternalLineWidth")
    protected BigInteger internalLineWidth;
    @XmlAttribute(name = "InternalRotationAngle")
    protected BigInteger internalRotationAngle;
    @XmlAttribute(name = "RulerMajor")
    protected BigInteger rulerMajor;
    @XmlAttribute(name = "RulerMinor")
    protected BigInteger rulerMinor;
    @XmlAttribute(name = "RulerUnit")
    protected BigInteger rulerUnit;
    @XmlAttribute(name = "WindowHeight")
    protected BigInteger windowHeight;
    @XmlAttribute(name = "WindowWidth")
    protected BigInteger windowWidth;
    @XmlAttribute(name = "WindowXPosition")
    protected BigInteger windowXPosition;
    @XmlAttribute(name = "WindowYPosition")
    protected BigInteger windowYPosition;
    @XmlAttribute(name = "ZoomLevel")
    protected BigInteger zoomLevel;
    @XmlAttribute(name = "BackColor")
    protected String backColor;
    @XmlAttribute(name = "EdgeBackColor")
    protected String edgeBackColor;
    @XmlAttribute(name = "EdgeForegroundColor")
    protected String edgeForegroundColor;
    @XmlAttribute(name = "EdgePattern")
    protected String edgePattern;
    @XmlAttribute(name = "FillPattern")
    protected String fillPattern;
    @XmlAttribute(name = "FontName")
    protected String fontName;
    @XmlAttribute(name = "ForegroundColor")
    protected String foregroundColor;

    /**
     * Gets the value of the boundingBoxScalable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBoundingBoxScalable() {
        return boundingBoxScalable;
    }

    /**
     * Sets the value of the boundingBoxScalable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBoundingBoxScalable(Boolean value) {
        this.boundingBoxScalable = value;
    }

    /**
     * Gets the value of the centerTracking property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCenterTracking() {
        return centerTracking;
    }

    /**
     * Sets the value of the centerTracking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCenterTracking(Boolean value) {
        this.centerTracking = value;
    }

    /**
     * Gets the value of the closed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isClosed() {
        return closed;
    }

    /**
     * Sets the value of the closed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClosed(Boolean value) {
        this.closed = value;
    }

    /**
     * Gets the value of the dither property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDither() {
        return dither;
    }

    /**
     * Sets the value of the dither property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDither(Boolean value) {
        this.dither = value;
    }

    /**
     * Gets the value of the fixedBoundingBox property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFixedBoundingBox() {
        return fixedBoundingBox;
    }

    /**
     * Sets the value of the fixedBoundingBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFixedBoundingBox(Boolean value) {
        this.fixedBoundingBox = value;
    }

    /**
     * Gets the value of the fontScaleable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFontScaleable() {
        return fontScaleable;
    }

    /**
     * Sets the value of the fontScaleable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFontScaleable(Boolean value) {
        this.fontScaleable = value;
    }

    /**
     * Gets the value of the gridFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGridFlag() {
        return gridFlag;
    }

    /**
     * Sets the value of the gridFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGridFlag(Boolean value) {
        this.gridFlag = value;
    }

    /**
     * Gets the value of the gridsnapFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGridsnapFlag() {
        return gridsnapFlag;
    }

    /**
     * Sets the value of the gridsnapFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGridsnapFlag(Boolean value) {
        this.gridsnapFlag = value;
    }

    /**
     * Gets the value of the pageCountSeq property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPageCountSeq() {
        return pageCountSeq;
    }

    /**
     * Sets the value of the pageCountSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPageCountSeq(Boolean value) {
        this.pageCountSeq = value;
    }

    /**
     * Gets the value of the pagebreakFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPagebreakFlag() {
        return pagebreakFlag;
    }

    /**
     * Sets the value of the pagebreakFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPagebreakFlag(Boolean value) {
        this.pagebreakFlag = value;
    }

    /**
     * Gets the value of the resizableFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isResizableFlag() {
        return resizableFlag;
    }

    /**
     * Sets the value of the resizableFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setResizableFlag(Boolean value) {
        this.resizableFlag = value;
    }

    /**
     * Gets the value of the rulerFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRulerFlag() {
        return rulerFlag;
    }

    /**
     * Sets the value of the rulerFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRulerFlag(Boolean value) {
        this.rulerFlag = value;
    }

    /**
     * Gets the value of the rulerGuideFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRulerGuideFlag() {
        return rulerGuideFlag;
    }

    /**
     * Sets the value of the rulerGuideFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRulerGuideFlag(Boolean value) {
        this.rulerGuideFlag = value;
    }

    /**
     * Gets the value of the showCanvas property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowCanvas() {
        return showCanvas;
    }

    /**
     * Sets the value of the showCanvas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowCanvas(Boolean value) {
        this.showCanvas = value;
    }

    /**
     * Gets the value of the showView property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowView() {
        return showView;
    }

    /**
     * Sets the value of the showView property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowView(Boolean value) {
        this.showView = value;
    }

    /**
     * Gets the value of the statusLineFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStatusLineFlag() {
        return statusLineFlag;
    }

    /**
     * Sets the value of the statusLineFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStatusLineFlag(Boolean value) {
        this.statusLineFlag = value;
    }

    /**
     * Gets the value of the toolpaletteFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isToolpaletteFlag() {
        return toolpaletteFlag;
    }

    /**
     * Sets the value of the toolpaletteFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setToolpaletteFlag(Boolean value) {
        this.toolpaletteFlag = value;
    }

    /**
     * Gets the value of the visualStateValid property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVisualStateValid() {
        return visualStateValid;
    }

    /**
     * Sets the value of the visualStateValid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisualStateValid(Boolean value) {
        this.visualStateValid = value;
    }

    /**
     * Gets the value of the wrapText property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWrapText() {
        return wrapText;
    }

    /**
     * Sets the value of the wrapText property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWrapText(Boolean value) {
        this.wrapText = value;
    }

    /**
     * Gets the value of the arrowStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowStyle() {
        return arrowStyle;
    }

    /**
     * Sets the value of the arrowStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowStyle(String value) {
        this.arrowStyle = value;
    }

    /**
     * Gets the value of the capStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapStyle() {
        return capStyle;
    }

    /**
     * Sets the value of the capStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapStyle(String value) {
        this.capStyle = value;
    }

    /**
     * Gets the value of the characterCellHden property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getCharacterCellHden() {
        return characterCellHden;
    }

    /**
     * Sets the value of the characterCellHden property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setCharacterCellHden(BigInteger value) {
        this.characterCellHden = value;
    }

    /**
     * Gets the value of the characterCellHnum property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getCharacterCellHnum() {
        return characterCellHnum;
    }

    /**
     * Sets the value of the characterCellHnum property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setCharacterCellHnum(BigInteger value) {
        this.characterCellHnum = value;
    }

    /**
     * Gets the value of the characterCellVden property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getCharacterCellVden() {
        return characterCellVden;
    }

    /**
     * Sets the value of the characterCellVden property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setCharacterCellVden(BigInteger value) {
        this.characterCellVden = value;
    }

    /**
     * Gets the value of the characterCellVnum property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getCharacterCellVnum() {
        return characterCellVnum;
    }

    /**
     * Sets the value of the characterCellVnum property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setCharacterCellVnum(BigInteger value) {
        this.characterCellVnum = value;
    }

    /**
     * Gets the value of the cornerRadiusX property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getCornerRadiusX() {
        return cornerRadiusX;
    }

    /**
     * Sets the value of the cornerRadiusX property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setCornerRadiusX(BigInteger value) {
        this.cornerRadiusX = value;
    }

    /**
     * Gets the value of the cornerRadiusY property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getCornerRadiusY() {
        return cornerRadiusY;
    }

    /**
     * Sets the value of the cornerRadiusY property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setCornerRadiusY(BigInteger value) {
        this.cornerRadiusY = value;
    }

    /**
     * Gets the value of the dashStyle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDashStyle() {
        return dashStyle;
    }

    /**
     * Sets the value of the dashStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDashStyle(String value) {
        this.dashStyle = value;
    }

    /**
     * Gets the value of the displayQuality property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDisplayQuality() {
        return displayQuality;
    }

    /**
     * Sets the value of the displayQuality property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDisplayQuality(String value) {
        this.displayQuality = value;
    }

    /**
     * Gets the value of the drawingHden property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getDrawingHden() {
        return drawingHden;
    }

    /**
     * Sets the value of the drawingHden property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setDrawingHden(BigInteger value) {
        this.drawingHden = value;
    }

    /**
     * Gets the value of the drawingHnum property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getDrawingHnum() {
        return drawingHnum;
    }

    /**
     * Sets the value of the drawingHnum property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setDrawingHnum(BigInteger value) {
        this.drawingHnum = value;
    }

    /**
     * Gets the value of the drawingWden property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getDrawingWden() {
        return drawingWden;
    }

    /**
     * Sets the value of the drawingWden property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setDrawingWden(BigInteger value) {
        this.drawingWden = value;
    }

    /**
     * Gets the value of the drawingWnum property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getDrawingWnum() {
        return drawingWnum;
    }

    /**
     * Sets the value of the drawingWnum property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setDrawingWnum(BigInteger value) {
        this.drawingWnum = value;
    }

    /**
     * Gets the value of the editorHeight property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getEditorHeight() {
        return editorHeight;
    }

    /**
     * Sets the value of the editorHeight property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setEditorHeight(BigInteger value) {
        this.editorHeight = value;
    }

    /**
     * Gets the value of the editorWidth property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getEditorWidth() {
        return editorWidth;
    }

    /**
     * Sets the value of the editorWidth property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setEditorWidth(BigInteger value) {
        this.editorWidth = value;
    }

    /**
     * Gets the value of the fontSize property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getFontSize() {
        return fontSize;
    }

    /**
     * Sets the value of the fontSize property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setFontSize(BigInteger value) {
        this.fontSize = value;
    }

    /**
     * Gets the value of the fontSpacing property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFontSpacing() {
        return fontSpacing;
    }

    /**
     * Sets the value of the fontSpacing property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFontSpacing(String value) {
        this.fontSpacing = value;
    }

    /**
     * Gets the value of the fontStyle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFontStyle() {
        return fontStyle;
    }

    /**
     * Sets the value of the fontStyle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFontStyle(String value) {
        this.fontStyle = value;
    }

    /**
     * Gets the value of the fontWeight property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFontWeight() {
        return fontWeight;
    }

    /**
     * Sets the value of the fontWeight property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFontWeight(String value) {
        this.fontWeight = value;
    }

    /**
     * Gets the value of the frameTitleAlign property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFrameTitleAlign() {
        return frameTitleAlign;
    }

    /**
     * Sets the value of the frameTitleAlign property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFrameTitleAlign(String value) {
        this.frameTitleAlign = value;
    }

    /**
     * Gets the value of the frameTitleOffset property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getFrameTitleOffset() {
        return frameTitleOffset;
    }

    /**
     * Sets the value of the frameTitleOffset property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setFrameTitleOffset(BigInteger value) {
        this.frameTitleOffset = value;
    }

    /**
     * Gets the value of the frameTitleSpacing property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getFrameTitleSpacing() {
        return frameTitleSpacing;
    }

    /**
     * Sets the value of the frameTitleSpacing property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setFrameTitleSpacing(BigInteger value) {
        this.frameTitleSpacing = value;
    }

    /**
     * Gets the value of the gridIntervalCnt property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getGridIntervalCnt() {
        return gridIntervalCnt;
    }

    /**
     * Sets the value of the gridIntervalCnt property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setGridIntervalCnt(BigInteger value) {
        this.gridIntervalCnt = value;
    }

    /**
     * Gets the value of the gridSnapCnt property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getGridSnapCnt() {
        return gridSnapCnt;
    }

    /**
     * Sets the value of the gridSnapCnt property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setGridSnapCnt(BigInteger value) {
        this.gridSnapCnt = value;
    }

    /**
     * Gets the value of the gridUnitCnt property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getGridUnitCnt() {
        return gridUnitCnt;
    }

    /**
     * Sets the value of the gridUnitCnt property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setGridUnitCnt(BigInteger value) {
        this.gridUnitCnt = value;
    }

    /**
     * Gets the value of the internalLineWidth property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getInternalLineWidth() {
        return internalLineWidth;
    }

    /**
     * Sets the value of the internalLineWidth property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setInternalLineWidth(BigInteger value) {
        this.internalLineWidth = value;
    }

    /**
     * Gets the value of the internalRotationAngle property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getInternalRotationAngle() {
        return internalRotationAngle;
    }

    /**
     * Sets the value of the internalRotationAngle property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setInternalRotationAngle(BigInteger value) {
        this.internalRotationAngle = value;
    }

    /**
     * Gets the value of the rulerMajor property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getRulerMajor() {
        return rulerMajor;
    }

    /**
     * Sets the value of the rulerMajor property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setRulerMajor(BigInteger value) {
        this.rulerMajor = value;
    }

    /**
     * Gets the value of the rulerMinor property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getRulerMinor() {
        return rulerMinor;
    }

    /**
     * Sets the value of the rulerMinor property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setRulerMinor(BigInteger value) {
        this.rulerMinor = value;
    }

    /**
     * Gets the value of the rulerUnit property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getRulerUnit() {
        return rulerUnit;
    }

    /**
     * Sets the value of the rulerUnit property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setRulerUnit(BigInteger value) {
        this.rulerUnit = value;
    }

    /**
     * Gets the value of the windowHeight property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getWindowHeight() {
        return windowHeight;
    }

    /**
     * Sets the value of the windowHeight property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setWindowHeight(BigInteger value) {
        this.windowHeight = value;
    }

    /**
     * Gets the value of the windowWidth property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getWindowWidth() {
        return windowWidth;
    }

    /**
     * Sets the value of the windowWidth property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setWindowWidth(BigInteger value) {
        this.windowWidth = value;
    }

    /**
     * Gets the value of the windowXPosition property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getWindowXPosition() {
        return windowXPosition;
    }

    /**
     * Sets the value of the windowXPosition property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setWindowXPosition(BigInteger value) {
        this.windowXPosition = value;
    }

    /**
     * Gets the value of the windowYPosition property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getWindowYPosition() {
        return windowYPosition;
    }

    /**
     * Sets the value of the windowYPosition property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setWindowYPosition(BigInteger value) {
        this.windowYPosition = value;
    }

    /**
     * Gets the value of the zoomLevel property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getZoomLevel() {
        return zoomLevel;
    }

    /**
     * Sets the value of the zoomLevel property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setZoomLevel(BigInteger value) {
        this.zoomLevel = value;
    }

    /**
     * Gets the value of the backColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackColor() {
        return backColor;
    }

    /**
     * Sets the value of the backColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackColor(String value) {
        this.backColor = value;
    }

    /**
     * Gets the value of the edgeBackColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdgeBackColor() {
        return edgeBackColor;
    }

    /**
     * Sets the value of the edgeBackColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdgeBackColor(String value) {
        this.edgeBackColor = value;
    }

    /**
     * Gets the value of the edgeForegroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdgeForegroundColor() {
        return edgeForegroundColor;
    }

    /**
     * Sets the value of the edgeForegroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdgeForegroundColor(String value) {
        this.edgeForegroundColor = value;
    }

    /**
     * Gets the value of the edgePattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdgePattern() {
        return edgePattern;
    }

    /**
     * Sets the value of the edgePattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdgePattern(String value) {
        this.edgePattern = value;
    }

    /**
     * Gets the value of the fillPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillPattern() {
        return fillPattern;
    }

    /**
     * Sets the value of the fillPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillPattern(String value) {
        this.fillPattern = value;
    }

    /**
     * Gets the value of the fontName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontName() {
        return fontName;
    }

    /**
     * Sets the value of the fontName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontName(String value) {
        this.fontName = value;
    }

    /**
     * Gets the value of the foregroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForegroundColor() {
        return foregroundColor;
    }

    /**
     * Sets the value of the foregroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForegroundColor(String value) {
        this.foregroundColor = value;
    }

}
